GUI
itlab-vision/dl-benchmark pull request #130
Opened 2020-04-12 11:58 UTC by Alexandra-Sidorova

Пулл реквест для проверки и отслеживания состояния.

2020-05-07 16:45 UTC, Alexandra-Sidorova commented
@valentina-kustikova, @KchnKchn, проверьте, пожалуйста, на правильность реализации паттерна MVP для некоторых действий с таблицей "Конфигурации развертки".

Я добавила презентер _deploy_presenter_ (папка _presenters_) для виджета _WidgetDeployConfigs_ из файла _view.widgets.widgets_config_, а также модели _DeployComputer_ (то, что будет внутри тегов <Computer></Computer>) и _DeployConfig_, который будет работать с xml файлами.

Стоит отметить, что все остальное, что не касается выше перечисленного (виджеты, кнопки и таблицы для других конфигураций) может быть переделано и удалено (сырая реализация).

Пока что добавлена реализация кнопки "Добавить информацию" и "Очистить таблицу", постаралась на базе них понять MVP. Кроме того, для кнопок "Загрузить таблицу" и "Сохранить таблицу" необходимо будет реализовать парсинг xml файлов. Есть ли какие-то у вас предложения по поводу питоновских пакетов для этого?

Для запроса информации о компьютере добавила диалоговое окно. Если внести не все данные, появится уведомление.

Таким образом, буду рада услышать ваши предложения, идеи и замечания.

Для представления прикрепляю [ссылку](https://imgur.com/a/tqJQyBW) на изображения.

2020-05-08 08:35 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self._view.buttons.addSignal.connect(self.handle_add_button)
@Alexandra-Sidorova, не все обработчики должны быть реализованы в Presenter. Все что касается форм, должно быть в формах. В Presenter должны быть лишь обработчики, которые отвечают за изменение модели. Этот обработчик должен быть в view

2020-05-08 08:40 UTC, KchnKchn commented on gui/view/dialogs.py
> +        return computer
@Alexandra-Sidorova, нарушение MVP. Здесь у вас Viewer взаимодействует с моделью минуя Presenter. По сути Viewer ничего не знает о модели и должен лишь возвращать данные, из заполненных форм

2020-05-08 08:43 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self._view.table.clear()
@Alexandra-Sidorova, Viewer - это такая сущность, которая отображает Model и позволяет менять ее состояние. Очистка означает, что сначала мы отчищаем структуру данных Model. А потом ее визуализируем, точнее визуализируем то, что ничего нет (пустая таблица)

2020-05-08 08:44 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self._view.table.update(self._model.computers)
@Alexandra-Sidorova, здесь должны быть получены данные с формы и переданы модели, чтобы она поменяла своё состояние

2020-05-08 08:45 UTC, KchnKchn commented on gui/models/deploy_config.py
> +        self.download_folder = download_folder
@Alexandra-Sidorova, поля должны быть закрыты и должен быть предоставлен интерфейс доступа к полям (сеттеры и геттеры)

2020-05-08 08:46 UTC, KchnKchn commented on gui/models/deploy_config.py
> +        self.computers.append(computer)
@Alexandra-Sidorova, DeployConfig должен иметь закрытые поля, методы, которые позволяют его модифицировать и он должен отправлять сигнал о том, что Model изменил свое состояние

2020-05-08 18:15 UTC, Alexandra-Sidorova commented
@KchnKchn, исправила замечания. После вашего комментария еще лучше поняла, как все это реализовывать. 

Добавила функцию удаления информации о компьютерах, которые находятся в выделенных строках (можно выбрать ячейки, по ним определятся строки).

2020-05-08 20:17 UTC, KchnKchn commented on gui/view/tables.py
> +        self.__selected_rows.reverse()
@Alexandra-Sidorova, это делается так:
```python
self.__selected_rows.sort(reverse = True)
```

2020-05-08 20:19 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self.__view.get_dialog_add_computer().addComputerSignal.connect(self.handle_add_computer)
@Alexandra-Sidorova, по сути Presenter ничего не должен знать о структуре Viewer и работать только с сигналами, которые приходят непосредственно от Viewer. Нужно организовать передачу полей от диалога к виджету, и виджет должен отправлять сигнал о том, что Model был модифицирован.

2020-05-08 20:23 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +                                  dialog.get_os(), dialog.get_download_folder())
@Alexandra-Sidorova, сигнал может быть не только без аргументов, он так же может содержать данные.
Вы можете описать сигнал как
```python
addComputerSignal = QtCore.pyqtSignal(str, str, str, str, str)
```
А потом описать функцию handle_add_computer так:
```python
def handle_add_computer(self, ip, login, password, os, folder)
```
И сигнал будет вызывать обработчик и передавать аргументы

2020-05-08 20:26 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self.__view.get_table().update(self.__model.get_computers())
@Alexandra-Sidorova, у Viewer должен быть метод update, который принимает Model. С точки зрения MVP это должно выглядеть так:
```python
self.__view.update(self.__model)
```

2020-05-08 20:28 UTC, KchnKchn commented on gui/models/deploy_config.py
> +        return self.__download_folder
@Alexandra-Sidorova, нужно добавить сеттеры, так как должна быть возможность редактировать уже существующую конфигурацию

2020-05-09 11:20 UTC, Alexandra-Sidorova commented on gui/presenters/deploy_presenter.py
> +        self.__view.get_table().update(self.__model.get_computers())
@KchnKchn, а тогда будет ли это верным, если Viewer будет иметь метод, который получает Model? Ведь вроде Viewer тоже не должен ничего знать о структуре Model, если я не ошибаюсь, как собственно Model ничего не должен знать о Viewer.

2020-05-09 11:35 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self.__view.get_table().update(self.__model.get_computers())
@Alexandra-Sidorova, в этом случае Model ничего не знает о Viewer. Тут есть два варианта: 1) Передавать Viewer Model и Viewer сам будет обращаться через интерфейс к Model. Такой вариант приемлем, но немного не по шаблону.
2) Передавать Viewer необходимые данные для отрисовки. Тогда Presenter будет обращаться к Model, брать необходимые данные и передавать их в Viewer для отрисовки через метод Update. Предпочтительный вариант

2020-05-10 19:35 UTC, KchnKchn commented on gui/models/deploy_config.py
> +            return computers
@Alexandra-Sidorova, нужно сделать просто
```python
    return computers
```
Не волнуйтесь, в этом случае он сам все скопирует и снаружи ваши поля не сломают

2020-05-10 19:41 UTC, KchnKchn commented on gui/presenters/deploy_presenter.py
> +        self.__view.get_dialog_add_computer().addComputerSignal.connect(self.handle_add_computer)
@Alexandra-Sidorova, это замечание еще в силе. Сигнал о том, что нужно добавить компьютер должен отправлять View. Вы должны внутри класса View организовать передачу данных от формы, Как вариант, в конструктор окна диалога вы можете передать, например, пустой список, в который при нажатии кнопки применить, запишутся введенные параметры, так как передача будет по ссылке, то владельцем этого списка будет View, и View сможет вызвать сигнал о том, что нужно добавить новый компьютер с нужными параметрами

2020-05-11 13:23 UTC, Alexandra-Sidorova commented
@KchnKchn, вроде как все поправила. Добавила поддержку изменения строки (компьютера).

2020-05-12 07:09 UTC, valentina-kustikova commented on gui/view/widgets/widgets_config.py
> +        self._deploy_presenter = DeployPresenter(self._widgets['Составить конфигурацию резвертки'], model)
Объекты модели и презентора не должны создаваться во вьюшке. Они должны быть созданы в основном приложении (презентор управляет всем процессом обновления). При создании презентора в конструктор необходимо передать необходимые объекты модели. При создании вьюшки необходимо передать объект презентора.

2020-05-15 08:37 UTC, Alexandra-Sidorova commented on gui/models/deploy_config.py
> +    updateSignal = QtCore.pyqtSignal(list)
@valentina-kustikova, а если сделать так:
Методы в презентере:
```
   def handle_del_button(self, indexes):
        self.__model.delete_computers(indexes)
        self.update_view(self.__model.get_computers())

    def handle_clear_button(self):
        self.__model.clear()
        self.update_view(self.__model.get_computers())

    def handle_add_computer(self, ip, login, password, os, download_folder):
        self.__model.add_computer(ip, login, password, os, download_folder)
        self.update_view(self.__model.get_computers())

    def handle_change_computer(self, row, ip, login, password, os, download_folder):
        self.__model.change_computer(row, ip, login, password, os, download_folder)
        self.update_view(self.__model.get_computers())

    def update_view(self, models):
        self.__view.update(models)
```

И соответственно, в моделе нет никаких сигналов:

```
class DeployConfig:

    def __init__(self):
        super().__init__()
        self.__computers = []

    def get_computers(self):
        return self.__computers

    def add_computer(self, ip, login, password, os, download_folder):
        self.__computers.append(DeployComputer(ip, login, password, os, download_folder))

    def change_computer(self, row, ip, login, password, os, download_folder):
        self.__computers[row] = DeployComputer(ip, login, password, os, download_folder)

    def delete_computer(self, index):
        self.__computers.pop(index)

    def delete_computers(self, indexes):
        for index in indexes:
            if index < len(self.__computers):
                self.delete_computer(index)

    def clear(self):
        self.__computers.clear()
```

Если это решение неверное, то тогда наверное стоит пойти в сторону Наблюдателей, но по этой реализации есть вопросы.
1. Кто является тогда Наблюдателем согласно паттерну MVP? View?
2. Список наблюдателей хранится в Моделе?

2020-05-19 16:16 UTC, Alexandra-Sidorova commented
Исправила замечания (кроме создания презентера во вьюшке, а не в мейне, собираюсь это сделать после реализации всех моделей и презентеров).

Добавила загрузку и сохранение таблиц. Таким образом, у Deploy configuration на данный момент вроде как полная реализация.

2020-07-06 12:03 UTC, Alexandra-Sidorova commented
Запушила коммиты за июнь. Сделала на этот момент все, что смогла. Вопросы остались по реализации.

1.  Как мне в диалоговом окне при добавлении теста в всплывающем меню вывести список моделей, данных? Как мне обратиться к этим данным? Если у меня в презенторе вьюшка это виджет только с таблицей тестов, а модель в виде только тестов. Не совсем понятно, как обращаться к тем данным, через что.
2. Еще в мае сделала поддержку удаленного скрипта и развертки. Правильно ли сделаны чтение и запись конфигов? Но по крайней мере все работает.

Извиняюсь, если очень поздно запушила :) Почему-то после учебного года во время сессии появилась невыносимая лень.

2020-07-06 21:06 UTC, KchnKchn commented
@a-sidorova, предлагаю созвониться и обсудить накопившиеся вопросы. Напишите в скайпе, договоримся.

2020-10-03 16:55 UTC, a-sidorova commented
@KchnKchn, добавила поддержку нескольких тестов в одну строчку для бенчмарк конфигурации. Вопрос возник. Нужна ли такая же поддержка для конфигураций удаленного запуска и развертывания?

А также в связи с этим заметила, что если загрузить конфигурацию из файла в систему, то соответственно в таблице будут отображаться  тесты, не собранные в группы. То бишь если в файле у нас было два одинаковых теста для OpenVINO, но с разными типами запуска (sync, async), то соответственно в таблице после загрузки у нас будут две почти одинаковые строчки - разные значения будут лишь в столбике <mode>. Надо ли добавлять поддержку группирования при загрузке?

Ну и в принципе можно уже начать ревьювить, чтобы потихоньку начать мне все разгребать :smile:

2020-10-14 09:40 UTC, KchnKchn requested changes
@a-sidorova, заревьювил код. Есть замечания. Я предлагаю пересмотреть структуру ваших скриптов. У вас очень большие файлы получились, предлагаю разнести все виджеты и данные по отдельным файлам. И дергать их как импорт. Будет намного читабельнее и понятнее.
Предлагаю что то вроде этого:
```
gui
|___model
|   |___models
|   |   |___model.py
|   |   |___models.py
|   |___data
|   |   |___data.py
|   |   |___dataset.py
|   |___benchmark_config
|   |   |___test.py
|   |   |___benchmark_config.py
|   |___remote_config
|   |   |___remote_config.py
|   |   |___remote_computer.py
|   |___deploy_config
|   |   |___deploy_config.py
|   |   |___deploy_computer.py
|   |___database.py
|___presenter
|   |___model_presenter
|   |   |___model_presenter.py
|   |___data_presenter
|   |   |___data_presenter.py
|   |___benchmark_presenter
|   |   |___benchmark_presenter.py
|   |___remote_start_presenter
|   |   |___remote_start_presenter.py
|   |___remote_deploy_presenter
|   |   |___remote_deploy_presenter.py
|   |___presenter.py
|__view
|   |___buttons
|   |   |___...
|   |___dialogs
|   |   |___...
|   |___tables
|   |   |___...
|   |___widgets
|   |   |___...
|   |___view.py
|___main.py

2020-10-14 09:40 UTC, KchnKchn commented on gui/models/models.py
> +            return False
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/models/models.py
> +            return False
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/presenters/presenters.py
> +        self.__update_view()
@a-sidorova, я бы выделил это как отдельного презентора модели, и класс презентеров бы просто его агрегировал. И вынес реализацию в отдельный файл.

2020-10-14 09:40 UTC, KchnKchn commented on gui/presenters/presenters.py
> +        self.__update_view()
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/presenters/presenters.py
> +        self.__update_view()
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/presenters/presenters.py
> +        self.__update_view()
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/presenters/presenters.py
> +        self.__view.update(self.__model)
@a-sidorova, аналогично

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/buttons.py
> +from PyQt5.QtWidgets import *
@a-sidorova, плохой импорт. Импортируйте только те виджеты, которые используете

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/dialogs.py
> +from PyQt5.QtWidgets import *
@a-sidorova, плохой импорт. Импортируйте только те виджеты, которые используете

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/main_window.py
> +from view.widgets.widgets_config import *
@a-sidorova, плохой импорт. Импортируйте только то, что используете

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/tables.py
> +from models.models import *
@a-sidorova, аналогично про импорты

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/widgets/widgets_config.py
> +from PyQt5.QtWidgets import *
@a-sidorova, аналогично про импорт

2020-10-14 09:40 UTC, KchnKchn commented on gui/view/widgets/widgets_data.py
> +from PyQt5.QtWidgets import *
@a-sidorova, аналогично про импорт

2020-10-22 13:25 UTC, a-sidorova commented
Изменения:
- Изменила структуру скриптов
- Добавила группировку тестов при чтении конфигурации бенчмарка
- Добавила файлы `__init__.py` для корректного import'a как пакетов

@KchnKchn, проверьте, пожалуйста. Кроме того, видимо, необходимо в файлах _requirements_windows.txt_ и _requirements_linux.txt_ добавить PyQt5, чтобы Travis CI не ругался на его импорты

2020-10-22 13:44 UTC, KchnKchn commented
> Изменения:
> 
> * Изменила структуру скриптов
> * Добавила группировку тестов при чтении конфигурации бенчмарка
> * Добавила файлы `__init__.py` для корректного import'a как пакетов
> 
> @KchnKchn, проверьте, пожалуйста. Кроме того, видимо, необходимо в файлах _requirements_windows.txt_ и _requirements_linux.txt_ добавить PyQt5, чтобы Travis CI не ругался на его импорты

@a-sidorova, По поводу requirements, да, в них нужно добавить pyqt5. Стяните текущий мастер себе в ветку и добавьте, тогда импорт пройдет. 
По поводу init.py. Это излишне. У вас при работе пути строятся от рута (от main.py). Но линтер этого не понимает. Хорошее решение это использовать import так:
Структура директорий такая:
```
dir
|___foo
|___|___bar
|___|___|___bar.py
|___|___foo.py
|___main.py
```
В bar.py у вас что то реализовано. Тогда в foo.py можно импортить так 
```python3
import .bar.bar
``` 
И это будет корректно. 
Тоже самое если такой вариант:
```
dir
|___foo
|___|___bar.py
|___|___foo.py
|___main.py
```
В foo.py импортить bar.py можно так 
```python3
import .bar
```
Линтер на такое ругаться не должен.

2020-10-22 16:24 UTC, a-sidorova commented
@KchnKchn , а если наоборот, в bar.py мне надо импортировать foo.py, то как прописывать? 

Или допустим, структура такая:

```
dir
|___foo
|___|___bar
|___|___|___bar.py
|___|___foo
|___|___|___foo.py
|___main.py
```

И опять, например, в bar.py нужно импортировать foo.py?

Если я не ошибаюсь, то тут без пакетов с `__init__.py` не обойтись, поскольку использовать абсолютный импорт тут не получится (проверила). Есть еще вариант с пакетом `os ` и `sys.path.insert()`, но я считаю, это костыль, использовать такое не хочется.

2020-10-22 16:45 UTC, KchnKchn commented
> @KchnKchn , а если наоборот, в bar.py мне надо импортировать foo.py, то как прописывать?
> 
> Или допустим, структура такая:
> 
> ```
> dir
> |___foo
> |___|___bar
> |___|___|___bar.py
> |___|___foo
> |___|___|___foo.py
> |___main.py
> ```
> 
> И опять, например, в bar.py нужно импортировать foo.py?
> 
> Если я не ошибаюсь, то тут без пакетов с `__init__.py` не обойтись, поскольку использовать абсолютный импорт тут не получится (проверила). Есть еще вариант с пакетом `os ` и `sys.path.insert()`, но я считаю, это костыль, использовать такое не хочется.

В таком случае делайте так в bar.py
```python
import ..foo.foo  # pylint: disable=E0402
```

2020-12-17 08:39 UTC, KchnKchn approved these changes

2020-12-17 08:39 UTC, merged