[TF] Inference
itlab-vision/dl-benchmark pull request #193
Opened 2020-10-14 08:16 UTC by Vladislav-Denisov

2020-11-25 17:31 UTC, KchnKchn requested changes
@Vladislav-Denisov, хорошо. Исправьте нейминг - замержу

2020-11-25 17:31 UTC, KchnKchn commented on src/inference/transformer.py
> +        return shape[1:]
@Vladislav-Denisov, плохой нейминг. Не понятно, что имеется ввиду. Я бы назвал так `get_shape_in_chw_order`

2020-11-27 08:03 UTC, Vladislav-Denisov commented on src/inference/transformer.py
> +        return shape[1:]
@KchnKchn, поправил

2020-12-11 14:08 UTC, KchnKchn approved these changes

2020-12-11 14:13 UTC, merged