[ConfigMaker] Quantization
itlab-vision/dl-benchmark pull request #250
Opened 2022-03-31 14:17 UTC by AlibekovMurad5202

2022-04-28 10:16 UTC, valentina-kustikova commented on src/configs/quantization_configuration_file_template.xml
> +<Parameters>
@AlibekovMurad5202, такое ощущение, что здесь используется табуляция вместо пробелов. Проверьте, пожалуйста, а то отступы какие-то слишком большие, сложно читать.

2022-04-28 10:16 UTC, valentina-kustikova commented on src/configs/quantization_configuration_file_template.xml
> +</Parameters>
@AlibekovMurad5202, для этого файла конфигурации необходимо в README.md добавить информацию по аналогии со всеми шаблонными конфигурациями, которые у нас есть.

2022-04-30 09:59 UTC, a-sidorova requested changes

2022-04-30 09:59 UTC, a-sidorova commented on src/config_maker/view/dialogs/quantization_config_dialog.py
> +        cancel_btn.clicked().connect(self.reject)
```suggestion
        ok_btn.clicked.connect(self.accept)  # pylint: disable=E1120
        cancel_btn.clicked.connect(self.reject)  # pylint: disable=E1120
```

Поправь так, пожалуйста, везде в PR.

Issue https://github.com/PyCQA/pylint/issues/6464

2022-04-30 09:59 UTC, a-sidorova commented on src/config_maker/model/quantization_config/quantized_model.py
> +            model_params[:idx_1],       # config_model_params (model_name, model (.xml), weights (.bin))
А можем ли мы как-то переиспользовать модели из класса Model?
Чтобы в табе Models в GUI отображался список моделей, а мы их переиспользовали, как это сделано в Benchmark и AccuracyChecker

2022-04-30 09:59 UTC, a-sidorova commented on src/config_maker/tags.py
> +# CONFIG_AC_CONFIG_TAG = 'AccuracyCheckerConfig'
Удали, пожалуйста, если все-таки не нужно

2022-10-14 22:38 UTC, AlibekovMurad5202 commented
@valentina-kustikova, @FenixFly, @a-sidorova, взгляните, пожалуйста

2022-10-27 00:33 UTC, closed without merging