[PyTorch] Added support of inference
itlab-vision/dl-benchmark pull request #361
Opened 2023-04-08 18:03 UTC by a-sidorova

2023-04-09 06:40 UTC, valentina-kustikova approved these changes

2023-04-09 09:06 UTC, a-sidorova commented
@valentina-kustikova добавила еще таблицу с валидационными результатами для классификационных моделей

2023-04-09 11:37 UTC, valentina-kustikova commented
> @valentina-kustikova добавила еще таблицу с валидационными результатами для классификационных моделей

Отлично. Надо еще добавить pytorch_models_checklist.md на уровень выше.

2023-04-16 19:55 UTC, a-sidorova commented
@valentina-kustikova обновила README, добавила поддержку бенчмаркинга, добавила поддержку в smoke тесты и добавила model checklist.
Только почему-то smoke tests CI красный - `Error: Process completed with exit code 255`. Правда, все тесты пройдены и `csv` файл собран.

2023-04-17 06:28 UTC, maslovaz commented
>Только почему-то smoke tests CI красный - `Error: Process completed with exit code 255`. Правда, все тесты пройдены и `csv` файл собран.

https://github.com/itlab-vision/dl-benchmark/blob/4358116f0aeff9e582e71d37639c2130842f93bc/test/smoke_test/run_bench_smoke_test.sh#L13
тут надо прибавить +1 тест
эта проверка добавлена специально (от баги-дубликация строк в csv репорте)

подумаю, как сделать эту проверку проще, без ручного подсчета тестов в конфиге

2023-04-17 07:21 UTC, a-sidorova commented
@maslovaz, а я и не обратила внимание на то, что пишет, что прошло 6 тестов, а на самом деле то уже 7 :smile:
Спасибо, поправила! Теперь CI зеленый

2023-04-17 08:43 UTC, maslovaz approved these changes

2023-04-17 09:50 UTC, ivikhrev commented on src/inference/inference_pytorch.py
> +    return predictions, time_infer
У pytorch есть [inference_mode](https://pytorch.org/docs/stable/generated/torch.inference_mode.htmll), наверное стоит его заиспользовать тут

2023-04-17 10:40 UTC, maslovaz commented
а запуск из файла не работает...
```
  File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 248, in main
    compiled_model = compile_model(model, device)
  File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 154, in compile_model
    module.to(device)
AttributeError: 'dict' object has no attribute 'to'
```

2023-04-17 10:46 UTC, a-sidorova commented
> а запуск из файла не работает...
> 
> ```
>   File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 248, in main
>     compiled_model = compile_model(model, device)
>   File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 154, in compile_model
>     module.to(device)
> AttributeError: 'dict' object has no attribute 'to'
> ```

А можете, пожалуйста, выслать командную строку?
Я пробовала экспортить `alexnet` в `alexnet.pth` и у меня работало. Поэтому интересно, какой кейс сломан. Спасибо!

2023-04-17 10:52 UTC, maslovaz commented
> А можете, пожалуйста, выслать командную строку? 

python3 ./src/inference/inference_pytorch.py -i ./test/smoke_test/black_square.jpg -b 1 -ni 10 --device CPU --model public/resnet-50-pytorch/resnet50-19c8e357.pth

2023-04-17 11:04 UTC, maslovaz commented
> > а запуск из файла не работает...
> > ```
> >   File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 248, in main
> >     compiled_model = compile_model(model, device)
> >   File "/home/zmas/code/dl-benchmark/src/inference/inference_pytorch.py", line 154, in compile_model
> >     module.to(device)
> > AttributeError: 'dict' object has no attribute 'to'
> > ```
> 
> А можете, пожалуйста, выслать командную строку? Я пробовала экспортить `alexnet` в `alexnet.pth` и у меня работало. Поэтому интересно, какой кейс сломан. Спасибо!

попробовала скачать pth и запустить с теми же параметрами, которые в смок тестах, тоже отвалилось
python3 ./src/inference/inference_pytorch.py -i ./test/smoke_test/black_square.jpg -is 1 3 224 224 -b 1 -ni 10 --input_name data --norm --mean 0.485 0.456 0.406 --std 0.229 0.224 0.225 --device CPU --model alexnet-owt-7be5be79.pth

2023-04-17 11:27 UTC, maslovaz requested changes
should work with pth models (discussed)

2023-04-17 11:33 UTC, valentina-kustikova commented on README.md
> +[pytorch]: https://pytorch.org/
Надо удалить последний слэш в ссылке.

2023-04-17 11:33 UTC, valentina-kustikova commented on results/pytorch_models_checklist.md
> +# Model validation and performance analysis status for MXNet
for PyTorch, а не MXNet

2023-04-17 11:33 UTC, valentina-kustikova commented on results/pytorch_models_checklist.md
> +Model | Availability in OMZ (2022.3)| Availability in the validation table |
@a-sidorova, вы здесь какой OMZ имеете ввиду? Когда я делала такую же табличку для MXNet, под OMZ я имела ввиду GluonCV OMZ, поэтому в столбце "наличие в OMZ" у меня везде плюсы стояли, а у вас встречаются минусы, вроде бы такого не должно быть.

2023-04-17 11:33 UTC, valentina-kustikova commented on src/benchmark/README.md
> +[pytorch]: https://pytorch.org/
Удалить слэш в конце.

2023-04-17 11:33 UTC, valentina-kustikova commented on src/inference/README.md
> +- `--outout_names` - название выхода модели. По умолчанию модель
output, а не outout

2023-04-17 11:33 UTC, valentina-kustikova commented on src/inference/inference_pytorch.py
> +    elif device == 'CUDA':
Имеет смысл сделать значение передаваемого параметра `NVIDIA GPU`, как в реализации MXNet.

2023-05-01 17:18 UTC, a-sidorova commented
> should work with pth models (discussed)

Насколько я понимаю, для файлов формата `.pth` нужен еще python скрипт `.py`, который содержит в себе архитектуру модели. Предлагаю это залить как отдельный PR после текущего.

2023-05-02 07:23 UTC, maslovaz commented
> > should work with pth models (discussed)
> 
> Насколько я понимаю, для файлов формата `.pth` нужен еще python скрипт `.py`, который содержит в себе архитектуру модели. Предлагаю это залить как отдельный PR после текущего.

ок, только я бы предложила в этом ПР тогда убрать упоминания pth из документации как минимум

2023-05-02 08:50 UTC, valentina-kustikova commented
> > > should work with pth models (discussed)
> > 
> > 
> > Насколько я понимаю, для файлов формата `.pth` нужен еще python скрипт `.py`, который содержит в себе архитектуру модели. Предлагаю это залить как отдельный PR после текущего.
> 
> ок, только я бы предложила в этом ПР тогда убрать упоминания pth из документации как минимум

А у нас вообще существуют такие модели в omz. Мы в понедельник обсуждали этот вопрос и пришли к тому, что таких моделей в omz быть не должно.

2023-05-02 08:53 UTC, maslovaz commented
> А у нас вообще существуют такие модели в omz. Мы в понедельник обсуждали этот вопрос и пришли к тому, что таких моделей в omz быть не должно.

полно .pth моделей, которые потом конвертируются в оникс специальным скриптом, но в оригинале это .pth, например resnet50-19c8e357.pth

2023-05-02 17:50 UTC, a-sidorova commented on results/validation/validation_results_pytorch.md
> +
Удалено

2023-05-02 17:50 UTC, a-sidorova commented on results/validation/validation_results_pytorch.md
> +
Удалено

2023-05-02 17:50 UTC, a-sidorova commented on src/benchmark/frameworks/pytorch/pytorch_test.py
> +        parameters.update({'Input shape': self.dep_parameters.input_shape})
Точно, спасибо!

2023-05-02 17:50 UTC, a-sidorova commented on src/inference/README.md
> +  в формате `.pth`.
Верно, когда исправляла, в этом месте упустила. Спасибо

2023-05-02 17:50 UTC, a-sidorova commented on src/inference/README.md
> +  (значение параметра `GPU`). По умолчанию принимает значение `CPU`.
В коде исправила, в README нет. Теперь поправила, спасибо

2023-05-02 17:50 UTC, a-sidorova commented on src/inference/README.md
> +  `JIT` (`just in time`) компилятором.
Исправлено

2023-05-02 17:50 UTC, a-sidorova commented on src/inference/README.md
> +                            --batch_size <batch_size>
Добавлено, спасибо

2023-05-02 17:50 UTC, a-sidorova commented on src/inference/inference_pytorch.py
> +        'input_shape': args.input_shape,
Исправила, спасибо!

2023-05-03 11:08 UTC, maslovaz commented on src/benchmark/frameworks/pytorch/pytorch_process.py
> +        model_pth = self._test.model.model
model_pth -> model_pt

2023-05-03 11:09 UTC, maslovaz commented on src/inference/README.md
> +python inference_pytorch.py --model <file_name>.pth \
```suggestion
python inference_pytorch.py --model <file_name>.pt \
```

2023-05-03 11:10 UTC, maslovaz commented on src/inference/inference_pytorch.py
> +    supported_files = ['pt']
supported_files -> supported_extensions? или supported_formats?

2023-05-03 17:15 UTC, a-sidorova commented on src/inference/README.md
> +python inference_pytorch.py --model <file_name>.pth \
Исправлено, спасибо

2023-05-03 17:15 UTC, a-sidorova commented on src/inference/inference_pytorch.py
> +    supported_files = ['pt']
Переименовала, спасибо

2023-05-03 17:15 UTC, a-sidorova commented on src/benchmark/frameworks/pytorch/pytorch_process.py
> +        model_pth = self._test.model.model
Исправила, спасибо

2023-05-03 17:17 UTC, maslovaz approved these changes

2023-05-03 18:02 UTC, a-sidorova commented
@valentina-kustikova взгляните тоже, пожалуйста

2023-05-04 06:40 UTC, ivikhrev commented on src/inference/inference_pytorch.py
> +import sys
```suggestion
#!/usr/bin/env python3
import sys
```

2023-05-04 07:14 UTC, a-sidorova commented on src/inference/inference_pytorch.py
> +import sys
Подскажите, пожалуйста, зачем эта строчка? :) Мы просто нигде это не добавляли

2023-05-04 07:17 UTC, a-sidorova commented on src/inference/transformer.py
> +
И правда. Большое спасибо! Поправила

2023-05-04 07:19 UTC, valentina-kustikova approved these changes

2023-05-04 07:19 UTC, valentina-kustikova commented on src/inference/README.md
> +  за один проход сети. По умолчанию равно `1`.
Описание `batch_size` добавилось в описание параметров скрипта для MXNet, а не PyTorch :)

2023-05-04 07:19 UTC, valentina-kustikova commented on src/inference/README.md
> +                            --batch_size <batch_size>
Добавилось в описание инференса с использованием MXNet

2023-05-04 07:24 UTC, a-sidorova commented on src/inference/README.md
> +  за один проход сети. По умолчанию равно `1`.
Точно, Readme разраслось достаточно сильно почти с одинаковым везде описанием :smile:
В любом случае я оставила этот параметр в `mxnet`, потому что он есть в аргументах для `inference_mxnet.py`
Спасибо!

2023-05-04 07:48 UTC, ivikhrev commented on src/inference/inference_pytorch.py
> +import sys
Это [shebang](https://stackoverflow.com/questions/7670303/purpose-of-usr-bin-python3-shebang), позволяет звать скрипт просто как исполняемый файл `./inference_pytorch.py`
Для этого еще файл стоит пометить как executable и в гите закоммитить.
```
chmod +x inference_pytorch.py
```

> Мы просто нигде это не добавляли

Можно во все ланчеры добавить, сделает локальные запуски чуть удобнее.

2023-05-05 06:31 UTC, maslovaz approved these changes

2023-05-05 08:49 UTC, valentina-kustikova approved these changes

2023-05-05 08:57 UTC, a-sidorova commented on src/inference/inference_pytorch.py
> +import sys
Предлагаю это тогда сделать в отдельном PR'e, потому что это не относится все-таки к поддержке PyTorch, скорее, добавлние всяких плюшек (более того, это нужно во всех лаунчерах). Создайте, пожалуйста, issue с данным предложением. Спасибо!

2023-05-05 12:02 UTC, FenixFly approved these changes

2023-05-05 15:09 UTC, ivikhrev commented on src/inference/inference_pytorch.py
> +import sys
ок

2023-05-05 15:10 UTC, ivikhrev approved these changes

2023-05-05 16:17 UTC, merged