TFLite and Pytorch CPP launcher, fps measure change and minor updates
itlab-vision/dl-benchmark pull request #395
Opened 2023-06-29 11:49 UTC by maslovaz

2023-06-30 07:41 UTC, valentina-kustikova commented on src/benchmark/README.md
> +- **Среднее количество кадров, обрабатываемое за секунду(frames per second, FPS)** -
Если я правильно поняла, то договорились, что теперь этот показатель будет использоваться для обоих режимов (и для синхронного, и для асинхронного), но введен он только в блоке, где описываются показатели для синхроннного интерфейса. Что не так?

2023-06-30 07:41 UTC, valentina-kustikova commented on src/benchmark/README.md
> +показатели Batch FPS).
Надо еще добавить комментарии на Wiki после того, как замержим PR.

2023-06-30 07:41 UTC, valentina-kustikova commented on src/configs/README.md
> +    Command line может отличаться для разных версий benchmark_app (Дает возможность переименования
Что имеется ввиду под Command line?

После скобки заглавная буква

2023-06-30 07:41 UTC, valentina-kustikova commented on src/configs/README.md
> +  (в виде `[FP32]` или `input1[F32],input2[FP32]`)
Форматирование, отступ пропал

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +You can download C++ distribution of PyTorch from official [site][pytorch] (cxx11 ABI needed, for Nvidia GPU select distribution for CUDA), or build it from sources ([official instruction][build-inst
Не больше 80 символов в строку.

NVIDIA

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +    ```
bash после трех кавычек

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +1. Clone Pytorch repo:
Лучше добавлять пустую строку после пункта, а то где-то так, а где-то по-другому написано

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +### CMake build
Пустая строка после заголовка

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +1. (Optional) Install python3 and essential modules:
Пустая строка после пункта

2023-06-30 07:41 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +    ```
Пустая строка после кода

2023-06-30 11:28 UTC, valentina-kustikova commented
@FenixFly, @a-sidorova, просьба, оперативно посмотреть текущий PR.

2023-06-30 12:36 UTC, valentina-kustikova commented on README.md
>      correctness of inference implementation for the benchmarked models.
При описании директории `cpp_dl_benchmark` надо вписать полный перечень доступных фреймворков (C++ API).

2023-06-30 12:37 UTC, valentina-kustikova commented
@maslovaz, @n-berezina-nn, просьба, после мержа текущего PR обновить страницы на Wiki. Спасибо!

2023-06-30 23:51 UTC, FenixFly requested changes

2023-06-30 23:51 UTC, FenixFly commented on src/configs/README.md
>  - Набор тегов для тестирования вывода средствами TensorFlow Lite:
TensorFlow Lite и TensorFlow Lite CPP?

2023-06-30 23:51 UTC, FenixFly commented on src/configs/benchmark_configuration_file_template.xml
> +    <Test>
Кажется также не хватает примеров конфига для TFLite и TFLite CPP

2023-07-03 09:18 UTC, maslovaz commented on src/configs/README.md
>  - Набор тегов для тестирования вывода средствами TensorFlow Lite:
конкретно тут - питоновый АПИ, обновлю

2023-07-03 09:21 UTC, maslovaz commented on test/smoke_test/smoke_config.xml
>              <InferenceFramework>OpenVINO DLDT</InferenceFramework>
мы измеряем через benchmark_app, поддержка как плюсового, так и питонового benchmark_app из опенвино уже давно есть

2023-07-03 09:40 UTC, maslovaz commented on src/cpp_dl_benchmark/common/utils/src/utils.cpp
> +    for (const auto [data_precision, precision_str] : precision_to_str_map) {
спасибо, добавлено

2023-07-03 09:41 UTC, maslovaz commented on src/cpp_dl_benchmark/pytorch_launcher/src/pytorch_launcher.cpp
> +    for (const auto [type, data_prectision] : dtype_to_precision_map) {
спасибо, добавлено

2023-07-03 09:41 UTC, maslovaz commented on src/inference/README.md
> +1. ONNX Runtime.
done

2023-07-03 09:41 UTC, maslovaz commented on src/configs/benchmark_configuration_file_template.xml
> +    <Test>
added

2023-07-03 09:41 UTC, maslovaz commented on src/configs/README.md
>  - Набор тегов для тестирования вывода средствами TensorFlow Lite:
done

2023-07-03 09:41 UTC, maslovaz commented on README.md
>      correctness of inference implementation for the benchmarked models.
done

2023-07-03 09:42 UTC, maslovaz commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +    ```
done

2023-07-03 09:42 UTC, maslovaz commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +### CMake build
done

2023-07-03 09:42 UTC, maslovaz commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +1. Clone Pytorch repo:
done

2023-07-03 09:42 UTC, maslovaz commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +    ```
done

2023-07-03 09:42 UTC, maslovaz commented on src/configs/README.md
> +  (в виде `[FP32]` или `input1[F32],input2[FP32]`)
done

2023-07-03 09:42 UTC, maslovaz commented on src/cpp_dl_benchmark/pytorch_launcher/README.md
> +You can download C++ distribution of PyTorch from official [site][pytorch] (cxx11 ABI needed, for Nvidia GPU select distribution for CUDA), or build it from sources ([official instruction][build-inst
done

2023-07-03 09:43 UTC, maslovaz commented on src/configs/README.md
> +    Command line может отличаться для разных версий benchmark_app (Дает возможность переименования
переписала немного текст

2023-07-03 09:43 UTC, maslovaz commented on src/benchmark/README.md
> +- **Среднее количество кадров, обрабатываемое за секунду(frames per second, FPS)** -
проблема только в ридми, обновила

2023-07-03 09:43 UTC, maslovaz commented on src/benchmark/README.md
> +  отношение полного количества обработанных изображений к полному времени инференса
done

2023-07-03 09:47 UTC, n-berezina-nn commented on src/benchmark/frameworks/intel_caffe/intel_caffe_process.py
> +        common_params = (f'-m {model_prototxt} -w {model_caffemodel} -i {dataset} -b {batch} -d {device}'
с точки зрения ланчера это опциональный аргумент, но с точки зрения запуска inference_benchmark скрипта это параметр обязательный, тк из файла отчета выпарсиваются значения метрик. и без передачи этого параметра это не получится, либо где-то хардкодить и поддерживать консистентность дефолтных названий репортов в ланчере и обертках, что тоже плохо.

2023-07-03 12:20 UTC, a-sidorova commented on src/benchmark/frameworks/intel_caffe/intel_caffe_process.py
> +        common_params = (f'-m {model_prototxt} -w {model_caffemodel} -i {dataset} -b {batch} -d {device}'
У меня возник данный комментарий, потому что в PR'e в большинстве скриптов написано через `self._add_optional_argument_to_cmd_line`, а в этом в одном месте сразу эксплиситно. Мы можем тогда, пожалуйста, выравнить поведение?

Спасибо!

2023-07-03 12:29 UTC, a-sidorova commented on test/smoke_test/smoke_config.xml
>              <InferenceFramework>OpenVINO DLDT</InferenceFramework>
Я, может, неправильно задала вопрос или ваш ответ не понимаю, но я имела в виду, что у нас smoke tests проверяют лишь python inference для фреймворков в то время, когда у нас есть поддержка C++ для того же PyTorch и TFLite теперь. Хотелось бы также проверять работоспособность и данных лаунчеров. Что думаете?

2023-07-04 06:14 UTC, maslovaz commented on test/smoke_test/smoke_config.xml
>              <InferenceFramework>OpenVINO DLDT</InferenceFramework>
Я думала, что вопрос именно про опенвино=)
обсудили вчера с @valentina-kustikova - тестирование плюсовых ланчеров в рамках github actions-плохая затея. у нас есть такой же смок тест во внутреннем CI на плюсовых ланчерах

2023-07-04 06:41 UTC, maslovaz commented on src/benchmark/frameworks/intel_caffe/intel_caffe_process.py
> +        common_params = (f'-m {model_prototxt} -w {model_caffemodel} -i {dataset} -b {batch} -d {device}'
@a-sidorova
выровняла

2023-07-04 06:55 UTC, a-sidorova approved these changes

2023-07-04 08:13 UTC, maslovaz commented
@FenixFly всё еще висит статус "requested changes"

2023-07-04 08:14 UTC, maslovaz commented
@valentina-kustikova посмотрите, пожалуйста, финально еще разок

2023-07-04 08:25 UTC, FenixFly approved these changes

2023-07-05 07:34 UTC, valentina-kustikova reviewed
@maslovaz, все ок. Написала один вопрос.

2023-07-05 07:34 UTC, valentina-kustikova commented on src/benchmark/README.md
> +- **Среднее количество кадров, обрабатываемых за секунду (frames per second, FPS)** -
По смыслу (если я правильно поняла) FPS для обоих режимов считается одинаково, а определения даются разные. Поправьте меня, пожалуйста. Если я права, то имеет смысл написать одинаковые определения для FPS и называть их по-русски одинаково.

2023-07-05 11:20 UTC, valentina-kustikova commented on src/benchmark/README.md
> +- **Среднее количество кадров, обрабатываемых за секунду (frames per second, FPS)** -
Мне Github показывает следующее:

Для latency-режима:
- **Среднее количество кадров, обрабатываемое за секунду (frames per second, FPS)** -
  отношение полного количества обработанных изображений к полному времени вывода.

Для troughput-режима:
- **Среднее количество кадров, обрабатываемых за секунду (frames per second, FPS)** -
  отношение произведения размера обрабатываемой "пачки" и числа итераций
  к общему времени выполнения всех запросов.

2023-07-05 11:27 UTC, maslovaz commented on src/benchmark/README.md
> +- **Среднее количество кадров, обрабатываемых за секунду (frames per second, FPS)** -
Нашла, не то сравнивала.
Спасибо, исправила!

2023-07-05 11:33 UTC, valentina-kustikova approved these changes

2023-07-05 11:35 UTC, merged

2023-07-05 11:35 UTC, maslovaz commented
@valentina-kustikova сегодня-завтра обновлю вики

2023-07-05 12:18 UTC, valentina-kustikova commented
> @valentina-kustikova сегодня-завтра обновлю вики

@maslovaz, спасибо!