Tflite validation
itlab-vision/dl-benchmark pull request #409
Opened 2023-10-06 16:45 UTC by IgorKonovalovAleks

2023-10-08 16:46 UTC, valentina-kustikova commented on results/tflite_models_checklist.md
> +resnet-50-tf|+-| +                                    |
Не надо такие огромные колонки делать. Верните, пожалуйста, как было. Это имеет смысл только для вашего редактора.

2023-10-10 17:15 UTC, IgorKonovalovAleks commented
@valentina-kustikova  исправил

2023-10-16 13:15 UTC, valentina-kustikova commented
@IgorKonovalovAleks, @FenixFly, работа по этой задаче завешена? Можно смотреть пулл-реквест?

2023-10-27 10:15 UTC, FenixFly requested changes

2023-10-27 10:15 UTC, FenixFly commented on results/validation/validation_results_tflite.md
> +densenet-121| Mean: [123.675,116.28,103.53].<br>Input scale: [58.395,57.12,57.375].                               | 0.3022473 liner, ocean liner<br>0.1322417 breakwater, groin, groyne, mole, bulwark,
Тут появились какие-то гигантские пробелы

2023-10-27 10:15 UTC, FenixFly commented on results/validation/validation_results_tflite.md
> +efficientnet_lite0_fp32_2.tflite| Mean: [127.0, 127.0, 127.0].<br>Input scale: [128.0].                                               |0.0890195 chickadee<br>0.0884429 bee eater<br>0.0799505 goldfinc
Тут появились какие-то гигантские пробелы

2023-10-27 10:15 UTC, FenixFly commented on results/validation/validation_results_tflite.md
> +efficientnet_lite1_fp32_2.tflite| Mean: [127.0, 127.0, 127.0].<br>Input scale: [128.0].                                               |0.0281865 wool, woolen, woollen<br>0.0269535 water bottle<br>0.0
Тут появились какие-то гигантские пробелы

2023-10-27 10:15 UTC, FenixFly commented on results/tflite_models_checklist.md
> +densenet-121|+-| + |
Тут появились пробелы слева и справа от плюсиков

2023-10-27 10:32 UTC, IgorKonovalovAleks commented
@FenixFly

2023-10-27 10:55 UTC, FenixFly requested changes

2023-10-27 10:55 UTC, FenixFly commented on results/tflite_models_checklist.md
> +lite-model_mobilenet_v1_100_224_fp32_1.tflite|+ ([link][mobilenet_v1_100_224_fp32_1])| + |
Тут тоже плюсики с пробелами остались

2023-10-27 11:20 UTC, IgorKonovalovAleks commented
@FenixFly

2023-10-27 11:26 UTC, valentina-kustikova approved these changes

2023-10-27 11:26 UTC, valentina-kustikova commented on results/validation/validation_results_tflite.md
> +-|---------------------------------------------------------------------------------------------------|-|
В шапке не надо ставить много пробелов и минусов. Должно быть как-то так:

Model | Parameters | Python API |
-|-|-|

2023-10-29 11:34 UTC, FenixFly approved these changes

2023-10-29 12:42 UTC, valentina-kustikova approved these changes

2023-10-29 12:42 UTC, merged