Инференс DGL
itlab-vision/dl-benchmark pull request #423
Opened 2023-10-29 16:26 UTC by Atikin-NT

Готов файл инференса по DGL с бэкендом PyTorch. В Readme добавил описание всех параметров, которые на данный момент поддерживаются, и пример запуска.

В файл `dgl_pytorch_auxiliary.py` вынес общие функции инференса PyTorch и инференса DGL.

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/README.md
> +> **Примечание**: если одновременно указать и `-ni / --number_iter` и `--time`, то будет учитываться тот параметр, при котором инферес работает дольше.
Знак `>` перед примечанием не нужен. Второй момент - надо писать не более 80 символов в строке.

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/README.md
> +1. DGL (PyTorch)
Надо использовать полное название библиотеки: `Digital Graph Library (DGL, PyTorch-based).`

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +    """
У нас не предусмотрено документирование функций, поэтому это излишне при интеграции.

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +def main() -> None:
Также не предусмотрено явное написание возвращаемых параметров.

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +        log.info(f'Write report to {args.report_path}')
Во всех скриптах инференса предусмотрена валидация моделей (возврат результата инференса) при выполнении только одной итерации вывода.

2023-10-31 06:12 UTC, valentina-kustikova commented on src/inference/inference_pytorch.py
> +            time_infer = loop_inference(num_iterations, test_duration)(inference_iteration)(device, inputs, model)
smoke-тесты после текущих изменений не стали падать?

Надо залить состояние текущего мастера и разрешить конфликты.

2023-11-01 07:23 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +        log.info(f'Write report to {args.report_path}')
В этом [коммите](https://github.com/itlab-vision/dl-benchmark/pull/423/commits/603cf41f1aad073dc783333fd8e924f0b7d15a2b) добавил вывод результата работы, но не получилось переиспользовать код PyTorch. Как я понял результатом в PyTorch является изображение, которое сохраняется в локальной директории. Ну у меня графы. В моей задаче результатом является массив, в котором перечислены классы вершин. Всего на графах существуют 3 самые популярные задачи: **классификация вершин**, **классификация ребер** и **предсказание новых ребер**. В зависимости от задачи будет разный вывод. Возможно стоит в будущем написать свой адаптер вывода для графов?

Пока сделал самый простой вывод в консоль.

2023-11-01 07:34 UTC, Atikin-NT commented on src/inference/inference_pytorch.py
> +            time_infer = loop_inference(num_iterations, test_duration)(inference_iteration)(device, inputs, model)
Я вернул всё как было, тк после [этого](https://github.com/itlab-vision/dl-benchmark/commit/e883af0455eb406dc9b4f4dcb164a74403be0754#diff-aac0f038d255b4dac8b96d7a9f4389e2a742a9a2662644ce56785128a72ea78d) коммита пришло очень много изменений в PyTorch и всё, что я вынес теперь работать не будет. За сегодня/завтра попробую аккуратно вынести пару функций.

У меня вопрос, как правильно делать smoke-тесты на своем форке? Сейчас смок тесты запускаются только на ветках `master`, `main` и `develop`. И чтобы потестить мне надо делать PR на мастер каждый раз на своем форке? Или может как-то можно настроить, чтобы я мог запускать smoke-тесты на своей ветке, не затронув остальные. С actions я начал взаимодействовать только в этом семестре, поэтому еще не знаю, как это правильно делать

2023-11-01 08:37 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +        log.info(f'Write report to {args.report_path}')
Да, для каждого типа задач пишется свой адаптер. Поэтому логично написать адаптер, который пишет в файл результаты работы для вашей задачи. В консоль ничего не надо бросать.

2023-11-01 08:41 UTC, valentina-kustikova commented on src/inference/inference_pytorch.py
> +            time_infer = loop_inference(num_iterations, test_duration)(inference_iteration)(device, inputs, model)
Smoke-тесты запускаются в готовых для межа пулл-реквестах, которые не находятся в состоянии Draft. Smoke-тесты можно запустить локально на машине, поскольку то всего лишь скрипт, который запускает inference_benchmark.py с переданным ему конфигом. Соответственно, когда вы будете писать поддержку запуска в бенчмарке, то вы расширите конфиг тестом со своими данными и запустить локально.

2023-11-01 08:43 UTC, Atikin-NT commented on src/inference/inference_pytorch.py
> +            time_infer = loop_inference(num_iterations, test_duration)(inference_iteration)(device, inputs, model)
Понял, спасибо за объяснение, всё сделаю

2023-11-02 08:13 UTC, FenixFly commented on src/inference/inference_pytorch.py
> +            time_infer = loop_inference(num_iterations, test_duration)(inference_iteration)(device, inputs, model)
Еще можно попробовать делать пулреквест из своей ветки в свой main, тогда тоже должны запускаться smoke тесты

2023-11-15 19:07 UTC, FenixFly requested changes

2023-11-15 19:07 UTC, FenixFly commented on src/benchmark/frameworks/known_frameworks.py
> +    dgl_pytorch = 'Deep Graph Library (DGL, PyTorch-based)'
Надо поменять на короткое название без запятых и скобок: 
dgl_pytorch = 'DGL PyTorch'

2023-11-15 19:07 UTC, FenixFly commented on test/smoke_test/smoke_config.xml
> +        <InferenceFramework>Deep Graph Library (DGL, PyTorch-based)</InferenceFramework>
Тоже поменять

2023-11-15 19:07 UTC, FenixFly commented on src/inference/inference_pytorch.py
> -def get_device_to_infer(device):
Вообще странно что из пайторча пропал это код, как работать не DGL моделям?

2023-11-15 20:50 UTC, Atikin-NT commented on src/inference/inference_pytorch.py
> -def get_device_to_infer(device):
Не совсем понял ваше замечание. Эту функцию я вынес в отдельный [файл](https://github.com/itlab-vision/dl-benchmark/pull/423/files/c6b6446da853298f65f353e4dace31a36eae03e9#diff-499c853ccc96c55f47a49965639e4f8a58250ccb1827471c31e41f118eba3175), где она повторяется точь в точь. Я это сделал, чтобы не было дублирования кода в проекте.

> DGL в качестве бэкенда использует PyTorch, поэтому некоторые функции идентичны.

2023-11-17 09:46 UTC, Atikin-NT commented on src/inference/inference_pytorch.py
> -def get_device_to_infer(device):
переименовал dgl_pytorch_auxiliary.py в pytorch_auxiliary.py

2023-11-18 16:51 UTC, valentina-kustikova requested changes

2023-11-18 16:51 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +    return {'output_result': result.detach().numpy()}
Способ подготовки выходных данных по смыслу зависит от задачи, поэтому здесь лучше поставить проверку параметра `task` по аналогии с другими скриптами инференса.

2023-11-18 16:51 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +    )
Конфигурирование logger'а изменилось в инференс скриптах, поскольку у нас сломалось логирование для PyTorch. Надо забрать изменения из master-ветки и исправить по аналогии с другими скриптами.

2023-11-18 16:51 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +                    log.info(result)
Это, наверное, осталось отладочное логирование?

2023-11-18 16:51 UTC, valentina-kustikova commented on test/smoke_test/smoke_config.xml
> +        <Dataset>
Надо поправить форматирование xml-тегов.

2023-11-28 07:17 UTC, Atikin-NT commented on src/benchmark/frameworks/dgl_pytorch/dgl_pytorch_process.py
> +        if task and task.lower() != 'n/a':
Согласен с вами: в n/a нет смысла. Я удалил эту часть условия

2023-11-28 07:18 UTC, Atikin-NT commented on src/inference/README.md
> +  решение задачи классификации. По умолчанию принимает значение
Пояснил, что к задачи классификации вершин графа

2023-11-28 07:19 UTC, Atikin-NT commented on src/inference/README.md
> +то будет учитываться тот параметр, при котором инферес работает дольше.
Это относилось к пункту списка. Удалил слово "Примечание" и сделал пояснение следующим предложением этого пункта, чтобы не было путаницы

2023-11-28 07:20 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +                        default='torchvision.models',
Это осталось от PyTorch. Удалил

2023-11-28 07:23 UTC, Atikin-NT commented on src/configs/README.md
> +      <InferenceMode>True</InferenceMode>
Да, на данный момент доступен только инференс. Я думал, что потом надо будет добавлять еще различные параметра и оставил, как заготовку на будущее. 

Чтобы не было путаницы удалил этот параметр.

2023-11-28 07:23 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +                        dest='inference_mode')
Полностью удалил этот параметр

2023-11-28 07:24 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +                    log.info(result)
Да, пропустил. Удалил эту строчку

2023-11-28 08:03 UTC, Atikin-NT commented on src/configs/README.md
> +      <InferenceMode>True</InferenceMode>
Из документации и форумов я узнал следующее:

DGL поддерживает параллелизм для обучения посредством torch.multiprocessing. Есть возможность использовать cuda и несколько графических процессов. Как я понял он в основном отвечает за разделение графов по процессам и сбор результатов.  Но даже если так, то тестить у себя дома я смогу только на нескольких процессах CPU, тк у меня AMD (не могу использовать cuda) и нет графической карты.

Параллельную обработку инференса я не нашел. Напишу на их форум, надеюсь помогут. 

Есть ли что-то похожее в PyTorch? Возможно получится найти через функции PyTorch.

2023-11-28 18:05 UTC, valentina-kustikova approved these changes

2023-11-28 18:08 UTC, valentina-kustikova commented on src/configs/README.md
> +      <InferenceMode>True</InferenceMode>
В PyTorch есть возможность запуска на GPU через назначение параметра device,  а также есть еще два параметра, отвечающих за параллелизм:

```python
 parser.add_argument('--num_inter_threads',
                        help='Number of threads used for parallelism between independent operations',
                        default=None,
                        type=int,
                        dest='num_inter_threads')
    parser.add_argument('--num_intra_threads',
                        help='Number of threads used within an individual op for parallelism',
                        default=None,
                        type=int,
                        dest='num_intra_threads')
```

2023-11-28 18:09 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2023-11-28 18:10 UTC, valentina-kustikova commented
@Atikin-NT, надо смержить с текущим состоянием мастер-ветки.

2023-11-28 19:02 UTC, FenixFly submitted a review, later dismissed

2023-12-08 19:14 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +    log.info(f'load module from {module_path}')
Load

2023-12-08 19:14 UTC, valentina-kustikova commented on src/inference/README.md
> +- `-mm / --module` - путь до Python модуля или относительный путь
Python-модуля

2023-12-08 19:15 UTC, valentina-kustikova commented on src/inference/README.md
> +  до Python файла с архитектурой модели.
Python-файла

2023-12-08 19:17 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +                        choices=['node-classification'],
У нас во всех скитах вывода предусмотрена задача `feedforward`, т.е. вывод без обработки выхода модели для получения показателей производительности. Имеет смысл и здесь по умолчанию сделать feedforward

2023-12-08 19:18 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +                        choices=['node-classification'],
В соответствии с этим необходимо обновить информацию в readme.

2023-12-08 19:20 UTC, valentina-kustikova commented on src/inference/io_graphs_adapter.py
> +class IOGprahAdapter(metaclass=abc.ABCMeta):
Буквы переставлены в названии класса, правильно - IOGraphAdapter

2023-12-08 19:21 UTC, valentina-kustikova commented on src/inference/inference_dgl_pytorch.py
> +        io = IOGprahAdapter.get_io_adapter(args, model_wrapper)
Буквы переставлены в названии класса, правильно - IOGraphAdapter

2023-12-08 19:23 UTC, valentina-kustikova commented on src/inference/io_graphs_adapter.py
> +        with open('out_graph_classification.csv', 'w+') as file:
Имеет смысл название выходного файла сделать параметром скрипта вывода.

2023-12-08 19:27 UTC, valentina-kustikova commented
@FenixFly, @n-berezina-nn, посмотрите, пожалуйста, бенчмакинг вывода с использованием Deep Graph Library (DGL).

2023-12-08 19:38 UTC, valentina-kustikova requested changes

2023-12-08 19:38 UTC, valentina-kustikova commented on requirements_frameworks.txt
> +dglgo
Надо еще добавить информацию о возможности использования DGL в README.md, который находится в коневой директории.

2023-12-17 19:25 UTC, valentina-kustikova submitted a review, later dismissed

2023-12-17 19:25 UTC, valentina-kustikova commented on src/inference/io_graphs_adapter.py
> +            return FeedForwardIO(args, io_model_wrapper)
```python
else:
    raise Exception...
```

2023-12-17 19:26 UTC, valentina-kustikova commented
@FenixFly, @n-berezina-nn, посмотрите,, пожалуйста.

2023-12-18 12:46 UTC, FenixFly submitted a review, later dismissed

2024-01-23 07:24 UTC, n-berezina-nn commented on src/inference/io_graphs_adapter.py
> +class IOGraphAdapter(metaclass=abc.ABCMeta):
Вероятно, есть смысл сразу сделать модуль из этого файла. Вынести каждый класс в отдельный файл, сложить всё в отдельную папку и создать __init__.py

2024-01-23 07:24 UTC, n-berezina-nn commented on src/inference/inference_dgl_pytorch.py
> +                             'NVIDIA_GPU (CPU by default)',
действительно поддерживается nvidia gpu или копи-паста?

2024-01-23 07:24 UTC, n-berezina-nn commented on src/inference/inference_dgl_pytorch.py
> +    if device.type == 'cuda':
запускали на cuda?

2024-01-23 07:24 UTC, n-berezina-nn commented on src/inference/io_graphs_adapter.py
> +class IOGraphAdapter(metaclass=abc.ABCMeta):
какой смысл делать этот класс абстрактным, если в нем нет ни одного абстрактного свойства и метода?
абстрактный класс используется для того, чтобы гарантировать, что в потомке будет реализован тот или иной метод или свойство.

2024-03-02 10:29 UTC, Atikin-NT commented
@valentina-kustikova, у меня есть вопрос по GPU для моего фреймворка. Я всё настроил для GPU, всё работает(проверил в google collab), но есть некоторые особенности. 

Фреймворк DGL очень чувствителен к наличию/отсутствию GPU и к версии cuda. Я провел исследования и есть след варианты.

+ Установить версию с CUDA, но она будет работать только на устройствах, где есть CUDA. Smoke тесты падают, тк actions без GPU. Еще есть очень жесткие зависимости по CUDA. Если установить не ту версию, то ничего не запустится.
+ Установить без CUDA. В этом случае проходят все smoke тесты, но нельзя будет запускать на GPU. Придется удалить эту версию и установить другую, которая поддерживает CUDA.

Я хочу в `requirements_frameworks.txt` указать обычную версию (без поддержки CUDA) и написать пояснение в README. Так будет сделать правильно или стоит как-то по другому? И если так, то в какой README об этом надо написать?

2024-03-03 06:20 UTC, valentina-kustikova commented
> @valentina-kustikova, у меня есть вопрос по GPU для моего фреймворка. Я всё настроил для GPU, всё работает(проверил в google collab), но есть некоторые особенности.
> 
> Фреймворк DGL очень чувствителен к наличию/отсутствию GPU и к версии cuda. Я провел исследования и есть след варианты.
> 
> * Установить версию с CUDA, но она будет работать только на устройствах, где есть CUDA. Smoke тесты падают, тк actions без GPU. Еще есть очень жесткие зависимости по CUDA. Если установить не ту версию, то ничего не запустится.
> * Установить без CUDA. В этом случае проходят все smoke тесты, но нельзя будет запускать на GPU. Придется удалить эту версию и установить другую, которая поддерживает CUDA.
> 
> Я хочу в `requirements_frameworks.txt` указать обычную версию (без поддержки CUDA) и написать пояснение в README. Так будет сделать правильно или стоит как-то по другому? И если так, то в какой README об этом надо написать?

@Atikin-NT, надо посмотреть, как это сделано для библиотеки PyTorch, там тоже есть поддержка запуска на GPU, но я не уверена, что она тестируется.

2024-03-05 17:15 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +    if device.type == 'cuda':
Да, проверил, всё работает

2024-03-05 17:16 UTC, Atikin-NT commented on src/inference/inference_dgl_pytorch.py
> +                             'NVIDIA_GPU (CPU by default)',
Поддерживает. Всё проверил

2024-03-07 18:37 UTC, valentina-kustikova approved these changes

2024-03-07 18:37 UTC, valentina-kustikova commented on src/inference/README.md
> +
Удалите, пожалуйста, лишние пустые строки в разделе LINKS, не видела ранее этого. Спасибо!

2024-03-07 18:38 UTC, valentina-kustikova commented
@n-berezina-nn, @FenixFly, посмотрите, пожалуйста.
Спасибо!

2024-03-07 20:08 UTC, Atikin-NT commented on src/inference/README.md
> +
Удалить все строки между ссылками или самую последнюю? Не совсем понял

2024-03-08 05:06 UTC, valentina-kustikova commented on src/inference/README.md
> +
Все пустые между ссылками.

2024-03-08 21:24 UTC, Atikin-NT commented on src/inference/README.md
> +
Готово 👍

2024-03-09 09:38 UTC, valentina-kustikova submitted a review, later dismissed

2024-04-15 11:40 UTC, FenixFly commented
@n-berezina-nn

2024-04-15 11:40 UTC, FenixFly commented
@n-berezina-nn

2024-04-15 11:49 UTC, n-berezina-nn approved these changes

2024-04-18 17:16 UTC, FenixFly approved these changes

2024-04-18 19:23 UTC, merged