[TVM] docker for tvm
itlab-vision/dl-benchmark pull request #434
Opened 2023-11-08 08:16 UTC by Rodimkov

2023-11-09 11:34 UTC, valentina-kustikova commented on docker/TVM/Dockerfile
> +    fi
Если я правильно понимаю, что еще должны быть ветки для TF lite и Caffe.

2023-11-09 11:34 UTC, valentina-kustikova commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
А точно порядок установки может быть такой? Не надо ли сначала поставить зависимости, а потом сам apache-tvm?

2023-11-09 11:56 UTC, FenixFly requested changes

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
python3 -m pip install

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +    pip3 install torch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION}; \
python3 -m pip install

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +    pip3 install tensorflow==${TF_VERSION}; \
python3 -m pip install

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +    pip3 install mxnet==${MXNET_VERSION}; \
python3 -m pip install

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +    pip uninstall -y numpy && pip install numpy==1.23.1; \
python3 -m pip install

2023-11-09 11:56 UTC, FenixFly commented on docker/TVM/Dockerfile
> +    pip3 install onnxruntime==${ONNX_VERSION} && pip3 install onnx==${ONNX_VERSION}; \
python3 -m pip install

2023-11-09 11:59 UTC, Rodimkov commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
apache-tvm не нужны другие библиотеки насколько я понимаю

2023-11-09 11:59 UTC, Rodimkov commented on docker/TVM/Dockerfile
> +    fi
Да, добавлю

2023-11-09 12:00 UTC, Rodimkov commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
А в чем будут отличия этих двух подходов?

2023-11-09 12:04 UTC, FenixFly commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
Подход python3 -m pip надежнее и не сломается при переходе от рутового пользователя и обратно

2023-11-09 12:05 UTC, Rodimkov commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
Но во всех остальных местах используется вариант с pip3 install https://github.com/itlab-vision/dl-benchmark/blob/8bbd4407ac6430cd856de2ab422c65a0993e89b4/docker/TensorFlow/Dockerfile#L18

2023-11-19 12:18 UTC, FenixFly commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
> Но во всех остальных местах используется вариант с pip3 install
> 
> https://github.com/itlab-vision/dl-benchmark/blob/8bbd4407ac6430cd856de2ab422c65a0993e89b4/docker/TensorFlow/Dockerfile#L18

Со временем все докеры будут переведены на python3 -m pip

2023-11-20 11:24 UTC, Rodimkov commented on docker/TVM/Dockerfile
> +RUN pip3 install apache-tvm==0.14.dev264
Вроде бы везде поправил

2023-11-24 18:57 UTC, valentina-kustikova approved these changes

2023-11-24 18:57 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2023-11-24 19:08 UTC, FenixFly approved these changes

2023-11-24 19:17 UTC, merged