TVM validation (top-10 models)
itlab-vision/dl-benchmark pull request #435
Opened 2023-11-08 12:54 UTC by valentina-kustikova

2023-11-11 18:28 UTC, ismukhin commented on .github/workflows/smoke_test.yml
> +          conda install caffe
Может можно попробовать выше в самом начале создать окружение командой: ```conda create -y -n caffe-env python=3.7``` и уже потом ставить caffe командой ```conda install -y -n caffe-env caffe ```. Ну и не забыть его активировать.

2023-11-11 18:30 UTC, valentina-kustikova commented on .github/workflows/smoke_test.yml
> +          conda install caffe
Да, я попробую, просто пока не за ноутбуком, позже.

2023-11-12 07:09 UTC, valentina-kustikova commented on .github/workflows/smoke_test.yml
> +          conda install caffe
@ismukhin, пофиксила, тест для Caffe работает. Думаю, что этот пулл-реквест надо замержить, а дальше обновление по результатам валидации средствами TVM, можно будет выложить отдельно.

2023-11-12 07:12 UTC, valentina-kustikova commented
@maslovaz, посмотрите, пожалуйста. Добавила тест для бенчмаркинга Caffe + пофиксила кое-какие моменты + сделала шаблонные файлы для последующей валидации моделей средствами TVM.

2023-11-12 10:58 UTC, ismukhin approved these changes

2023-11-13 16:28 UTC, valentina-kustikova commented
@maslovaz, @n-berezina-nn, посмотрите, пожалуйста, чтобы мы могли залить для последующей валидации.
Спасибо!

2023-11-16 15:50 UTC, FenixFly requested changes

2023-11-16 16:16 UTC, valentina-kustikova commented on src/inference/inference_tensorflow.py
> +                        default=[1, 1, 1],
Нет, не должно быть, у меня на входе 3 вещественных числа, а не строка.

2023-11-16 16:17 UTC, valentina-kustikova commented on src/inference/inference_caffe.py
> +                        default=[1, 1, 1],
Нет, у меня на входе 3 вещественных числа, а не строка.

2023-11-16 16:18 UTC, valentina-kustikova commented on test/smoke_test/smoke_config_caffe.xml
> +            <Mean>104.0 117.0 123.0</Mean>
Нет, на входе скрипта инференса не строка, а 3 вещественных числа.

2023-11-16 16:20 UTC, FenixFly approved these changes

2023-11-16 16:22 UTC, merged