Add sh for mmdnn converter
itlab-vision/dl-benchmark pull request #440
Opened 2023-11-13 15:24 UTC by SergeyBoRss

2023-11-13 16:38 UTC, valentina-kustikova commented on src/model_converters/mmdnn_converter/install_mmdnn_linux_x86_64.sh
> +export PATH=$PATH:/home/user/.local/bin
А зачем нам среда с openvino? Причем вы ее создаете, активируете, а потом в ней создаете еще одну среду, не деактивируя предыдущую?

2023-11-13 16:38 UTC, valentina-kustikova commented on src/model_converters/mmdnn_converter/install_mmdnn_linux_x86_64.sh
> +pip install -r requirements.txt
Аналогично, создали, активировали, установили пакеты, а дальше надо деактивировать.

2023-11-14 21:26 UTC, FenixFly requested changes

2023-11-14 21:26 UTC, FenixFly commented on src/model_converters/mmdnn_converter/install_mmdnn_linux_x86_64.sh
> +sudo apt install python3-pip
Лучше попробовать поменять на conda install pip. Apt - пакетный менеджер в основной системе, и я не уверен что он ставит pip3.6 в энвайрмент, а не в основную систему для всех питонов

2023-11-22 13:21 UTC, FenixFly commented on src/model_converters/mmdnn_converter/install_mmdnn_linux_x86_64.sh
> +export PATH=$PATH:/home/user/.local/bin
удалено

2023-11-22 13:22 UTC, valentina-kustikova approved these changes

2023-11-22 13:22 UTC, FenixFly approved these changes

2023-11-23 09:15 UTC, merged