Инференс Spektral
itlab-vision/dl-benchmark pull request #444
Opened 2023-11-17 10:21 UTC by ArchiMikael

Готовые файлы инференса, бенчмарка и теста для Spektral. Readme файлы пока что не изменял.

С автоматическим запуском тестов может быть проблема, поскольку для нормальной загрузки моделей требуется загрузка из формата .keras, что не поддерживается более старыми версиями Tensorflow. Хотелось бы узнать, стоит ли ради этого добавлять новый workflow, или можно подредактировать существующий?

2023-11-18 17:12 UTC, valentina-kustikova commented
> Готовые файлы инференса, бенчмарка и теста для Spektral. Readme файлы пока что не изменял.
> 
> С автоматическим запуском тестов может быть проблема, поскольку для нормальной загрузки моделей требуется загрузка из формата .keras, что не поддерживается более старыми версиями Tensorflow. Хотелось бы узнать, стоит ли ради этого добавлять новый workflow, или можно подредактировать существующий?

Надо создать отдельный job по аналогии с работой, которая создана для смок-теста inference_caffe.py.

2023-11-18 17:26 UTC, valentina-kustikova requested changes

2023-11-18 17:26 UTC, valentina-kustikova commented on src/benchmark/frameworks/spektral/spektral_parametrs_parser.py
> +#TODO: Check if Tensorflow framework-dependent parameters affect Spektral behavior
Может быть есть параметры, которые влияют на параллельность исполнения вычислений?

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +                             '(Modern Tensorflow doesnt support anything but CPU)',
Не поняла, что здесь имелось ввиду.

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +            raise ValueError('Attemting to import unsopported dataset.')
Attempt to import unsupported dataset.

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +    if task == 'node-classification':
Из возможных значений параметра задачи следует, что поддерживается 2 типа задач, а подготовка выходов написана только для одного. В дополнение обработка выхода должна выполняться в классе-наследнике IOAdapter, а здесь только преобразование в виду, который поддерживает адаптер.

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +                    level=log.INFO, stream=sys.stdout)
Конфигурирование logger сейчас исправлено. Надо залить к себе мастер-ветку и исправить по аналогии с другими инференс-скриптами.

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +        log.warning("Modern Tensorflow required for Spektral doesn't support any devices but CPU. Device will be switched.")
Странный комментарий с точки зрения языка.

2023-11-18 17:26 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +def prepare_input_loader(input_, batch_size):
Это должно быть частью адаптера входов-выходов.

2023-11-18 17:28 UTC, valentina-kustikova commented
@ArchiMikael, надо исправить стиль кодирования.

2023-11-23 11:59 UTC, FenixFly requested changes

2023-11-23 11:59 UTC, FenixFly commented on requirements_frameworks.txt
> +spektral
Нужно зафиксировать текущую версию spektral

2023-11-23 12:35 UTC, valentina-kustikova requested changes

2023-11-23 12:35 UTC, valentina-kustikova commented on test/smoke_test/run_bench_smoke_test_spektral.sh
> +curl -o working_dir_smoke/spektral/model.keras https://raw.githubusercontent.com/ArchiMikael/spektral/main/model.keras
Модель и test_graph.bin лучше положить туда же, где модель для DGL.

@FenixFly, что думаешь?

2023-11-23 12:35 UTC, valentina-kustikova commented
@ArchiMikael, для последних изменений не проходят смок-тесты и проверка стиля кодирования. Необходимо внести изменения.

2023-12-08 19:55 UTC, valentina-kustikova requested changes

2023-12-08 19:55 UTC, valentina-kustikova commented on src/benchmark/frameworks/spektral/spektral_parametrs_parser.py
> +# TODO: Check if Tensorflow framework-dependent parameters affect Spektral behavior
Думаю, что стоит удалить комментарий. Если задача актуальна, то надо создать issue осле того, как пулл-реквест будет залит.

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/README.md
> +- `-i / --input` - путь до графа или (расширение `.bin`).
`...или (...` что-то недописано?

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/README.md
> +  По умолчанию производится приведение к виду таблицы.
Во всех скриптах по умолчанию feedforward, т.е. режим вывода без обработки результатов с целью получения показателей производительности.

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +                        default='node-classification',
Во всех скриптах по умолчанию feedforward, т.е. режим вывода без обработки результатов с целью получения показателей производительности.

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +    log.info(f'Wrote report to {args.report_path}')
Writing

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/inference_spektral.py
> +            log.info(f'Inference results:\n{result}')
Во всех скриптах вывода этот блок выглядит так, как написано ниже. Надо привести в соответствие.
```python
        if not args.raw_output:
            if args.number_iter == 1:
                try:
                    log.info('Converting output tensor to print results')
                    result = prepare_output(result, args.output_names, args.model_name, args.task, args)
                    log.info('Inference results')
                    io.process_output(result, log)
                except Exception as ex:
                    log.warning('Error when printing inference results. {0}'.format(str(ex)))

        log.info(f'Performance results:\n{json.dumps(inference_result, indent=4)}')
```

2023-12-08 19:55 UTC, valentina-kustikova commented on src/inference/io_adapter_spektral.py
> +class IOAdapter_Spektral(metaclass=abc.ABCMeta):
Можно ли отнаследовать этот класс от нашего абстрактного IOAdapter?

2023-12-18 17:29 UTC, ArchiMikael commented on src/benchmark/frameworks/spektral/spektral_parametrs_parser.py
> +# TODO: Check if Tensorflow framework-dependent parameters affect Spektral behavior
Удалил комментарий. Можно будет открыть issue, если полностью перевести всё на формат сохранения SavedModel (не факт, что получится) и перейти на более старую версию Tensorflow (я проверял ту, которая используется в основном проекте, Spektral продолжает работать и использует ускорение от GPU).

2023-12-18 17:30 UTC, ArchiMikael commented on src/inference/README.md
> +- `-i / --input` - путь до графа или (расширение `.bin`).
Забыл удалить после копирования с другого описания.

2023-12-18 17:32 UTC, ArchiMikael commented on src/inference/io_adapter_spektral.py
> +class IOAdapter_Spektral(metaclass=abc.ABCMeta):
Перевёл на наследование от IOAdapter, но пришлось сделать дубликат класса FeedForwardIO для Spektral, поскольку для него не имеют значения "имена" входных и выходных слоёв.

2023-12-25 10:48 UTC, ArchiMikael commented
@valentina-kustikova, стоит ли загружать все требуемые фреймворки, или просто добавить ещё одну дополнительную загрузку, чтобы не падало из-за cv2?

2024-01-03 19:31 UTC, valentina-kustikova submitted a review, later dismissed

2024-01-03 19:31 UTC, valentina-kustikova commented on test/smoke_test/run_bench_smoke_test_spektral.sh
> +curl -o working_dir_smoke/spektral/model.keras https://raw.githubusercontent.com/ArchiMikael/spektral/main/model.keras
@FenixFly, надо создать репозиторий для моделей Spektral аналогично DGL.

@ArchiMikael, соответственно надо заменить ссылку.

2024-01-03 19:37 UTC, valentina-kustikova commented
@ArchiMikael, смок-тесты для Spektral упали, надо пофиксить и залить изменения.

2024-03-18 05:44 UTC, valentina-kustikova approved these changes

2024-04-28 19:50 UTC, valentina-kustikova submitted a review, later dismissed

2024-05-06 04:43 UTC, n-berezina-nn submitted a review, later dismissed

2024-05-06 12:07 UTC, valentina-kustikova commented
@ArchiMikael, пулл-реквест заапрувили, разрешите, пожалуйста, конфликты, и зальем. Спасибо!

2024-05-06 12:36 UTC, ArchiMikael commented
@valentina-kustikova, сделано

2024-05-07 04:44 UTC, valentina-kustikova approved these changes

2024-05-07 06:03 UTC, valentina-kustikova commented
@FenixFly, заапрувь, пожалуйста. Слетел аппрув Натальи, чтобы не отвлекать ее повторно. Спасибо!

2024-05-07 08:47 UTC, FenixFly approved these changes

2024-05-07 08:47 UTC, merged