[OpenVINO][RISC-V] Added cross-compilation build instruction
itlab-vision/dl-benchmark pull request #445
Opened 2023-11-19 07:58 UTC by a-sidorova

2023-11-19 11:39 UTC, a-sidorova commented
@valentina-kustikova @FenixFly взгляните, пожалуйста. Наконец-то поборола сборку Python API 😃

2023-11-19 12:25 UTC, FenixFly requested changes

2023-11-19 12:25 UTC, FenixFly commented on src/build_scripts/openvino/riscv64/Dockerfile
> +    gcc g++ python3 python3-pip python3-venv python3-dev && \
Ниже используется -DPYBIND11_PYTHON_EXECUTABLE_LAST=/usr/bin/python3.10 , можно ли тут тоже apt install python3.10 а не просто python3 указать?

2023-11-19 12:25 UTC, FenixFly commented on src/build_scripts/openvino/riscv64/Dockerfile
> +    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../openvino_riscv64_gnu -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/custom_riscv64.toolchain.cmake \
-DCMAKE_INSTALL_PREFIX=../../openvino_riscv64_gnu я бы тут абсолютный путь написал, для установки, а не относительный, чтобы знать где искать его в докере

2023-11-23 09:26 UTC, valentina-kustikova requested changes

2023-11-23 09:26 UTC, valentina-kustikova commented on src/build_scripts/openvino/riscv64/README.md
> +Install and configure Docker using [guide](../../../../docker/README).
Я бы предложила оформить в виде списка.

2023-11-23 09:26 UTC, valentina-kustikova commented on src/build_scripts/openvino/riscv64/README.md
> +Clone [OpenVINO][ov_repo] repository.
Аналогично предложила бы оформить в виде списка.

2023-12-08 10:20 UTC, FenixFly approved these changes

2023-12-08 19:13 UTC, merged