Scripts for building TFLite for Risc-V
itlab-vision/dl-benchmark pull request #446
Opened 2023-11-20 05:51 UTC by PPlastova

2023-11-23 11:55 UTC, FenixFly approved these changes

2023-11-23 12:29 UTC, valentina-kustikova requested changes

2023-11-23 12:30 UTC, valentina-kustikova commented
Сборка Python API планируется сюда же добавить или пойдет отдельно?

2023-12-08 06:33 UTC, valentina-kustikova commented
@PPlastova, внесите, пожалуйста, исправления, чтобы можно было замержить. Спасибо!

2023-12-17 19:48 UTC, valentina-kustikova approved these changes

2023-12-17 19:49 UTC, valentina-kustikova commented
@PPlastova, внесла небольшие правки по форматированию readme прямо в вашу ветку.

@FenixFly, посмотри, пожалуйста.

2023-12-18 12:45 UTC, FenixFly approved these changes

2023-12-18 12:49 UTC, merged