tflite segmentation adapter + deeplabv3 validation
itlab-vision/dl-benchmark pull request #457
Opened 2023-11-29 10:09 UTC by IgorKonovalovAleks

2023-12-06 13:00 UTC, valentina-kustikova commented on src/inference/inference_tensorflowlite.py
> +            log.info('Result image was saved to {0}'.format(out_img))
В функции `prepare_output` надо преобразовать выходной тензор сети в формат, который обрабатывается классом `ClassificationIO`, а уже там делается все необходимое для сохранения.

2023-12-08 20:00 UTC, valentina-kustikova requested changes

2023-12-08 20:01 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2023-12-08 20:01 UTC, valentina-kustikova commented
@IgorKonovalovAleks, надо разрешить конфликты.

2023-12-11 11:20 UTC, FenixFly requested changes

2023-12-11 11:20 UTC, FenixFly commented on src/inference/io_adapter.py
> +        result_layer_name = 0
Очень странное изменение. Есть вероятность, что это поломает classification модели

2023-12-12 08:12 UTC, valentina-kustikova requested changes

2023-12-12 08:12 UTC, valentina-kustikova commented on src/inference/io_adapter.py
> +        self.load_color_map("color_map.txt")
Никаких изменений в `io_adapter.py` не должно быть. Если что-то надо изменить в формате данных, то необходимо это делать в `prepare_output`.

2023-12-14 17:25 UTC, IgorKonovalovAleks commented on src/inference/io_adapter.py
> +        result_layer_name = 0
Это же адаптер для сегментации, разве он имеет какие-то отношение к классификации?

Если оставить как было, то при результат не выводится, а в консоли появляется ошибка:
[ WARNING ] Error when printing inference results. only integer scalar arrays can be converted to a scalar index

2023-12-14 19:59 UTC, valentina-kustikova commented on src/inference/io_adapter.py
> +        result_layer_name = 0
@IgorKonovalovAleks, думаю, что @FenixFly хотел сказать, что ваши изменения могут поломать валидацию сегментационных моделей в других фреймворках.

2023-12-16 07:44 UTC, IgorKonovalovAleks commented
@valentina-kustikova посмотрите пожалуйста

2023-12-16 19:19 UTC, valentina-kustikova requested changes

2023-12-16 19:19 UTC, valentina-kustikova commented on results/validation/validation_results_tflite.md
> +Model | Python|
Python -> Python API

2023-12-16 19:19 UTC, valentina-kustikova commented on src/inference/inference_tensorflowlite.py
> +
Удалите, пожалуйста, пустую строку.

2023-12-17 19:27 UTC, valentina-kustikova approved these changes

2023-12-17 19:27 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2023-12-23 05:00 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста, чтобы мы могли оперативно замержить эти изменения в мастер. Спасибо!

2023-12-24 19:35 UTC, FenixFly commented
@IgorKonovalovAleks нужно еще в редмишке https://github.com/itlab-vision/dl-benchmark/blob/master/src/inference/README.md дописать что у inference_tensorflowlite.py появился task segmentation

2023-12-25 04:38 UTC, merged