[TVM] TFLite, MXNet gluoncv detection models
itlab-vision/dl-benchmark pull request #463
Opened 2023-12-13 19:13 UTC by ismukhin

2023-12-14 19:57 UTC, valentina-kustikova commented
@ismukhin, немного поправила файлы с результатами валидации напрямую в вашей ветке.

2023-12-20 19:46 UTC, valentina-kustikova commented on src/model_converters/tvm_converter/tvm_converter.py
> +class TensorFlowLiteToTVMConverter(Converter):
Надо обновить src/inference/README.md в части описания скриптов вывода моделей в разных форматах средствами TVM, поскольку появился tflite

2023-12-22 12:37 UTC, FenixFly requested changes

2023-12-22 12:37 UTC, FenixFly commented on requirements_frameworks.txt
> +apache-tvm==0.14.dev170
@ismukhin пожалуйста обновитесь до apache-tvm==0.14.dev264 (которая сейчас в докере) и сравните вывод на одной-двух картинках, что выход не поменялся

2023-12-23 05:03 UTC, valentina-kustikova commented on requirements_frameworks.txt
> +apache-tvm==0.14.dev170
@FenixFly, это не имеет смысла, поскольку здесь указана версия, используемая для запуска смок-тестов. Если мы будем при переходе от версии к версии фреймворка валидировать все модели, то здесь надо только и заниматься.

2023-12-23 17:13 UTC, ismukhin commented on requirements_frameworks.txt
> +apache-tvm==0.14.dev170
@valentina-kustikova, успеваю, сделаю.

2023-12-23 20:22 UTC, ismukhin commented
@valentina-kustikova, немного намудрил с гитом :). У меня не получилось подтянуть изменения по нормальному, пришлось сделать ребейз, вылезли эти коммиты. Я их ревертнул, сейчас проблем не должно быть.

2023-12-24 04:50 UTC, valentina-kustikova commented on src/inference/inference_tvm_tensorflowlite.py
> +                        help='Path to an .pb or .meta file with a trained model.',
@ismukhin, наверное, здесь неудачный копи-паст. Не pb и meta, а tflite?

2023-12-24 11:45 UTC, ismukhin commented on src/inference/inference_tvm_tensorflowlite.py
> +                        help='Path to an .pb or .meta file with a trained model.',
Исправлено

2023-12-24 11:48 UTC, valentina-kustikova commented
@ismukhin, надо влить изменения из мастера и разрешить конфликты. Спасибо!

2023-12-24 12:18 UTC, ismukhin commented
@valentina-kustikova, готово

2023-12-24 12:40 UTC, valentina-kustikova approved these changes

2023-12-24 12:41 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2023-12-24 12:49 UTC, FenixFly approved these changes

2023-12-24 12:54 UTC, merged

2023-12-24 13:10 UTC, FenixFly commented
> @FenixFly, посмотри, пожалуйста. 

Заапрувил