download and convert script
itlab-vision/dl-benchmark pull request #464
Opened 2023-12-14 19:56 UTC by IgorKonovalovAleks

2023-12-14 20:02 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels
> +#!/bin/bash
Файл должен иметь расширение .sh

2023-12-14 20:02 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels
> +omz_downloader --name mobilenet-v1-1.0-224-tf
Может, имеет смысл организовать цикл о моделям, чтобы не дублировать командные стоки загрузки и конвертации?

omz_downloader может загрузить сазу набор моделей.

2023-12-16 07:44 UTC, IgorKonovalovAleks commented
@valentina-kustikova

2023-12-16 19:25 UTC, valentina-kustikova requested changes

2023-12-16 19:25 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels.sh
> +python3 ./src/model_converters/tflite_converter.py --model-path ./public/mobilenet-v3-small-1.0-224-tf/mobilenet_v3_small_224_1.0_float.savedmodel --input-names input_1 --input-shapes [1,224,224,3] -
Есть несколько предложений:

1. Путь до скрипта `tflite_converter.py` должен быть аргументом или хотя бы константой, которая объявлена в самом начале скрипта.
1. Путь до директории, где хранятся все модели, тоже должен быть аргументом или хотя бы константой, которая объявлена в самом начале скрипта.
1. Можно создать несколько согласованных массивов с параметрами запуска скрипта `tflite_converter.py`: `model_paths`, `input_names`, `input_shapes`, `output_names`, `src_frameworks`. Дальше реализовать цикл обхода моделей, в котором вызывать конвертер с набором соответствующих параметров.

2023-12-17 19:44 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels.sh
> +model_paths=('./mobilenet-v3-small-1.0-224-tf/mobilenet_v3_small_224_1.0_float.savedmodel' './mobilenet-v3-large-1.0-224-tf/mobilenet_v3_large_224_1.0_float.savedmodel' './resnet-50-tf/resnet_v1-50.p
1. `./` излишне писать, лучше при формировании строки `${models_path}/${model_paths[$i]}`.
2. Надо отформатировать код, чтобы в строке было не более 80 символов. Если я правильно помню, то обычный перенос между элементами разрешен, но надо проверить.

2023-12-17 19:44 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels.sh
> +converter_path='./src/model_converters/tflite_converter.py'
```bash
benchmark_dir='./dl-benchmark'
converter_path='${benchmark_dir}/src/model_converters/tflite_converter.py'
```

2023-12-17 19:44 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels.sh
> +cd dl-benchmark/
```bash
cd $benchmark_dir
```

2023-12-17 19:44 UTC, valentina-kustikova commented on docker/TensorFlowLite/downloadmodels.sh
> +omz_converter --list ./../models.lst
Странная директория сейчас :)

```bash
omz_downloader --list ${benchmark_dir}/docker/TensorFlowLite/models.lst
omz_converter --list ${benchmark_dir}/docker/TensorFlowLite/models.lst
```

2023-12-22 18:41 UTC, IgorKonovalovAleks commented
@valentina-kustikova

2023-12-23 04:47 UTC, valentina-kustikova approved these changes

2023-12-24 14:07 UTC, FenixFly approved these changes

2023-12-24 14:34 UTC, merged