[TVM] Script to convert bencmarked models to the TVM format
itlab-vision/dl-benchmark pull request #467
Opened 2023-12-19 21:01 UTC by valentina-kustikova

@FenixFly, скрипт конвертации моделей выложила. Докер-файл есть. Шаблонный конфигурационный файл для запуска экспериментов есть в чате, там надо вставить необходимые пути и размножить по количеству тестируемых пачек. В принципе для запуска экспериментов с неоптимизированными моделями есть все необходимое, просьба - запустить на хосте и в докере и выложить результаты.

2023-12-20 19:31 UTC, valentina-kustikova commented
@ismukhin, @FenixFly, тесты пофиксила, посмотрите, пожалуйста.

2023-12-20 19:51 UTC, ismukhin approved these changes

2023-12-20 20:23 UTC, FenixFly approved these changes

2023-12-21 00:00 UTC, FenixFly requested changes

2023-12-21 00:00 UTC, FenixFly commented on docker/TVM/convert_models_to_tvm.sh
> +pip install apache-tvm
и версию apache-tvm

2023-12-21 07:50 UTC, FenixFly approved these changes

2023-12-21 09:38 UTC, merged