Smoke tests changes and other improvements
itlab-vision/dl-benchmark pull request #483
Opened 2024-01-12 09:26 UTC by spartanezka

Rewrite smoke tests to pytest

2024-01-14 01:03 UTC, FenixFly commented on src/cpp_dl_benchmark/rknn_launcher/src/rknn_launcher.cpp
> +        // TODO: @i.vikhrev try with newer ndk.
Думаю стоит убрать строку с TODO, сделать issue

2024-01-14 01:04 UTC, FenixFly commented on src/cpp_dl_benchmark/rknn_launcher/src/rknn_launcher.cpp
> +    // TODO: enable if we would measure models with batch
Думаю стоит убрать строку с TODO, сделать issue

2024-01-14 01:06 UTC, FenixFly commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +        cmake -DDCMAKE_SYSTEM_PROCESSOR=aarch64,
в файлах выше запятые заменены на '\', стоит сделать также

2024-01-14 01:08 UTC, FenixFly commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +        cmake -DCMAKE_TOOLCHAIN_FILE=<dl-benchmark>/src/cpp_dl_benchmark/cmake/aarch64_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TFLITE_XNNPACK_LAUNCHER=ON -DBUILD_TFLITE_GPU_LAUNCHER=ON -DT
строка слишком длинная, можно разбить символов \\, как сделано выше

2024-01-14 10:30 UTC, valentina-kustikova reviewed
Добавила комментарии. Вопрос касательно картинок: насколько допускает лицензия на  эти картинки их выкладывать к нам в репозиторий?

2024-01-14 10:30 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +        cmake -DCMAKE_TOOLCHAIN_FILE=<dl-benchmark>/src/cpp_dl_benchmark/cmake/aarch64_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TFLITE_XNNPACK_LAUNCHER=ON -DBUILD_TFLITE_GPU_LAUNCHER=ON -DT
Имеет смысл разбить длинные строки, чтобы можно их было просматривать без прокрутки.

2024-01-14 10:30 UTC, valentina-kustikova commented on src/inference/io_adapter.py
> +        h, w = result.shape[2:]
Такое изменение точно не сломало обработку результатов сегментационных моделей OpenVINO? Проводилась валидация инференса OpenVINO для какой-либо сегментационной модели, которая ранее была проверена?

2024-01-14 10:30 UTC, valentina-kustikova commented on tests/smoke_test/configs/dl_models/AlexNet_Pytorch.xml
> +<?xml version="1.0" encoding="utf-8"?>
В названии файла Py**T**orch

2024-01-15 08:00 UTC, spartanezka commented on tests/smoke_test/configs/dl_models/AlexNet_Pytorch.xml
> +<?xml version="1.0" encoding="utf-8"?>
имя конфига расшифровывается так: <имя модели>_< inference framework >_<некоторые параметры, важные для данного случая>

2024-01-15 08:22 UTC, spartanezka commented on src/cpp_dl_benchmark/rknn_launcher/src/rknn_launcher.cpp
> +        // TODO: @i.vikhrev try with newer ndk.
https://github.com/itlab-vision/dl-benchmark/issues/485

2024-01-15 08:23 UTC, spartanezka commented on src/cpp_dl_benchmark/rknn_launcher/src/rknn_launcher.cpp
> +    // TODO: enable if we would measure models with batch
https://github.com/itlab-vision/dl-benchmark/issues/486

2024-01-15 08:51 UTC, spartanezka commented on src/cpp_dl_benchmark/rknn_launcher/README.md
> +The tool allows to measure deep learning models inference performance on Rockchip NPU with [RKNN API][RKNN]. For measurements you'll need a Rockchip device with NPU on board. RKNPU2 supports next pla
https://github.com/itlab-vision/dl-benchmark/issues/470#issuecomment-1891602232

2024-01-15 08:56 UTC, spartanezka commented on src/inference/io_adapter.py
> +        h, w = result.shape[2:]
@asesorov

2024-01-15 08:57 UTC, spartanezka commented
> Добавила комментарии. Вопрос касательно картинок: насколько допускает лицензия на эти картинки их выкладывать к нам в репозиторий?

@asesorov

2024-01-15 09:18 UTC, asesorov commented
> Добавила комментарии. Вопрос касательно картинок: насколько допускает лицензия на эти картинки их выкладывать к нам в репозиторий?

Картинки взяты из датасетов VOC2012, MS COCO и lyft-udacity-challenge (лицензия CC0)

2024-01-15 09:24 UTC, asesorov commented on src/inference/io_adapter.py
> +        h, w = result.shape[2:]
Проверка проводилась на модели pspnet-pytorch из OMZ (взята из чеклиста). Похожая проблема с шейпами была в Instance segmentation, как выяснилось, использовался устаревший формат (OpenVINO 2021.3), в связи с чем для Instance segmentation выкачивается legacy-модель из OpenVINO storage. Возможно, следует обновить сегментационную часть io-adapter'а для последней версии OpenVINO.

2024-01-16 04:14 UTC, valentina-kustikova commented on src/cpp_dl_benchmark/tflite_launcher/README.md
> +
Надо удалить пустые строки между ссылками.

2024-01-16 04:14 UTC, valentina-kustikova commented on src/inference/io_adapter.py
> +        h, w = result.shape[2:]
pspnet-pytorch не валидировалась, у нас в массовых экспериментах фигурирует только deeplabv3. Для нее валидация не сломалась?

2024-01-16 04:14 UTC, valentina-kustikova commented on tests/smoke_test/README.md
> +   ```
bash в начале блока с кодом

2024-01-16 04:14 UTC, valentina-kustikova commented on tests/smoke_test/README.md
> +   ```
bash в начале блока с кодом

2024-01-16 04:14 UTC, valentina-kustikova commented on tests/smoke_test/configs/dl_models/AlexNet_Pytorch.xml
> +<?xml version="1.0" encoding="utf-8"?>
Я имела ввиду, что буква t маленькая в названии файла, хотя в других названиях сохранен регистр имен фреймворков :)

2024-01-16 14:01 UTC, spartanezka commented
Изменения в io adapter были отменены, модель deeplabv3 поставлена на проверку

2024-01-16 18:43 UTC, valentina-kustikova submitted a review, later dismissed

2024-01-16 23:00 UTC, FenixFly requested changes

2024-01-16 23:00 UTC, FenixFly commented on src/cpp_dl_benchmark/tflite_launcher/src/tflite_launcher.cpp
> +#include <nlohmann/json.hpp>
дублирование строки с include

2024-01-17 07:15 UTC, asesorov approved these changes

2024-01-17 11:51 UTC, FenixFly approved these changes

2024-01-17 12:10 UTC, merged