[TVM] add detection models to .sh script
itlab-vision/dl-benchmark pull request #494
Opened 2024-02-14 13:27 UTC by ismukhin

2024-02-14 16:24 UTC, valentina-kustikova submitted a review, later dismissed

2024-02-14 17:47 UTC, FenixFly commented
В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Строка 37 дублирует строку 38, ее можно удалить.
@ismukhin

2024-02-14 17:49 UTC, FenixFly requested changes

2024-02-14 17:49 UTC, FenixFly commented on docker/TVM/convert_models_to_tvm.sh
> +pip install mxnet=1.9.1
==

2024-02-14 18:05 UTC, FenixFly requested changes

2024-02-14 18:05 UTC, FenixFly commented on docker/TVM/convert_models_to_tvm.sh
> +conda activate tvm_convert_python3.9
поменять на tvm_convert_mxnet_python3.9

2024-02-14 19:05 UTC, ismukhin commented
> В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Правильная версия apache-tvm видимо нам особенно важна. Строка 37 дублирует строку 38, ее можно удалить.
> 
> С версиями по умолчанию у меня не сконвертировалась pytorch модель ========== Converting resnet-50-pytorch to ONNX Conversion to ONNX command: /home/vasiliev/miniconda3/envs/tvm/bin/python -- /home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob
> 
> Traceback (most recent call last): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 187, in main() File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 179, in main model = load_model(args.model_name, args.weights, File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 126, in load_model with prepend_to_path(model_paths): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 49, in **enter** sys.path = self._preprended_paths + sys.path TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> 
> FAILED: resnet-50-pytorch
> 
> @ismukhin

Немного не понял место, где вызывается конвертация pytorch модели в onnx?

2024-02-14 19:06 UTC, ismukhin commented
> > В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Правильная версия apache-tvm видимо нам особенно важна. Строка 37 дублирует строку 38, ее можно удалить.
> > С версиями по умолчанию у меня не сконвертировалась pytorch модель ========== Converting resnet-50-pytorch to ONNX Conversion to ONNX command: /home/vasiliev/miniconda3/envs/tvm/bin/python -- /home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob
> > Traceback (most recent call last): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 187, in main() File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 179, in main model = load_model(args.model_name, args.weights, File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 126, in load_model with prepend_to_path(model_paths): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 49, in **enter** sys.path = self._preprended_paths + sys.path TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> > FAILED: resnet-50-pytorch
> > @ismukhin
> 
> Немного не понял место, где вызывается конвертация pytorch модели в onnx?

Во время конвертации модели из omz?

2024-02-14 19:10 UTC, FenixFly commented
> > > В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Правильная версия apache-tvm видимо нам особенно важна. Строка 37 дублирует строку 38, ее можно удалить.
> > > С версиями по умолчанию у меня не сконвертировалась pytorch модель ========== Converting resnet-50-pytorch to ONNX Conversion to ONNX command: /home/vasiliev/miniconda3/envs/tvm/bin/python -- /home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob
> > > Traceback (most recent call last): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 187, in main() File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 179, in main model = load_model(args.model_name, args.weights, File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 126, in load_model with prepend_to_path(model_paths): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 49, in **enter** sys.path = self._preprended_paths + sys.path TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> > > FAILED: resnet-50-pytorch
> > > @ismukhin
> > 
> > 
> > Немного не понял место, где вызывается конвертация pytorch модели в onnx?
> 
> Во время конвертации модели из omz?

Вызывается в строке 103. У меня кажется в 2022.3 модель не конвертировалась. Надо проверить в какой версии openvino-dev модель сконвертируется, и зафиксировать ее

2024-02-14 20:16 UTC, valentina-kustikova commented
> > > > В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Правильная версия apache-tvm видимо нам особенно важна. Строка 37 дублирует строку 38, ее можно удалить.
> > > > С версиями по умолчанию у меня не сконвертировалась pytorch модель ========== Converting resnet-50-pytorch to ONNX Conversion to ONNX command: /home/vasiliev/miniconda3/envs/tvm/bin/python -- /home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob
> > > > Traceback (most recent call last): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 187, in main() File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 179, in main model = load_model(args.model_name, args.weights, File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 126, in load_model with prepend_to_path(model_paths): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 49, in **enter** sys.path = self._preprended_paths + sys.path TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> > > > FAILED: resnet-50-pytorch
> > > > @ismukhin
> > > 
> > > 
> > > Немного не понял место, где вызывается конвертация pytorch модели в onnx?
> > 
> > 
> > Во время конвертации модели из omz?
> 
> Вызывается в строке 103. У меня кажется в 2022.3 модель не конвертировалась. Надо проверить в какой версии openvino-dev модель сконвертируется, и зафиксировать ее. Чтобы узнать версии работающих библиотек внутри всех энвайрментов, можно запустить с дефолтом, но в конце вырезать удаление энвайрментов из системы, и посмотреть что там установилось

Насколько я помню, модель из пакета torchvision.

2024-02-14 20:32 UTC, ismukhin commented
> > > > > В начале скрипта несколько раз ставится openvino-dev, apache-tvm, tensorflow-addons, tensorflow-probability, onnx-tf без указания версий. Пожалуйста, добавьте версии, которые сейчас ставятся у вас при запуске скприта. Правильная версия apache-tvm видимо нам особенно важна. Строка 37 дублирует строку 38, ее можно удалить.
> > > > > С версиями по умолчанию у меня не сконвертировалась pytorch модель ========== Converting resnet-50-pytorch to ONNX Conversion to ONNX command: /home/vasiliev/miniconda3/envs/tvm/bin/python -- /home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/vasiliev/_dev/itlab/dl-benchmark-vasilev/docker/TVM/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob
> > > > > Traceback (most recent call last): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 187, in main() File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 179, in main model = load_model(args.model_name, args.weights, File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 126, in load_model with prepend_to_path(model_paths): File "/home/vasiliev/miniconda3/envs/tvm/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py", line 49, in **enter** sys.path = self._preprended_paths + sys.path TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> > > > > FAILED: resnet-50-pytorch
> > > > > @ismukhin
> > > > 
> > > > 
> > > > Немного не понял место, где вызывается конвертация pytorch модели в onnx?
> > > 
> > > 
> > > Во время конвертации модели из omz?
> > 
> > 
> > Вызывается в строке 103. У меня кажется в 2022.3 модель не конвертировалась. Надо проверить в какой версии openvino-dev модель сконвертируется, и зафиксировать ее. Чтобы узнать версии работающих библиотек внутри всех энвайрментов, можно запустить с дефолтом, но в конце вырезать удаление энвайрментов из системы, и посмотреть что там установилось
> 
> Насколько я помню, модель из пакета torchvision.

Я сломал себе энвайромент, поэтому это займет определенное время (что-то с conda внутри моей системы)

2024-02-14 21:10 UTC, ismukhin commented
Я хоть и сломал себе свои энвайроменты, но при таких версиях пакетов вроде сконвертировалось всё

2024-02-15 14:15 UTC, FenixFly approved these changes

2024-02-15 15:07 UTC, valentina-kustikova commented
@ismukhin, в ветке какие-то конфликты. Разрешите, пожалуйста.

2024-02-18 18:40 UTC, valentina-kustikova approved these changes

2024-02-18 18:40 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2024-02-18 18:52 UTC, FenixFly approved these changes

2024-02-18 18:56 UTC, merged