Tf2onnx
itlab-vision/dl-benchmark pull request #514
Opened 2024-03-17 22:11 UTC by Vav1L0N

2024-03-19 15:16 UTC, valentina-kustikova commented
@Vav1L0N, структуру описания надо сделать по аналогии с [PR#510](https://github.com/itlab-vision/dl-benchmark/pull/510).

2024-03-21 12:22 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/convert_tf_to_onnx.py
> +# Настройка логгирования
Удалите, пожалуйста, этот комментарий.

2024-03-21 12:22 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/convert_tf_to_onnx.py
> +                        dest='graphdef')
А tf2onnx умеет конвертировать только pb-модели? А другие формате TensorFlow моделей?

2024-04-17 19:03 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/README.md
> +## Запуск скрипта конвертации
Перед запуском нужно описать еще установку в отдельном подразделе.

2024-04-17 19:03 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/README.md
> +и сконвертированных в ONNX-формат
Надо явно написать, с использованием каких скриптов производился запуск инференса.

2024-04-17 19:04 UTC, valentina-kustikova commented
@Vav1L0N, исправьте, пожалуйста, замечания. Также есть вопрос.

2024-04-17 19:05 UTC, valentina-kustikova commented
@FenixFly, посмотри, пожалуйста.

2024-04-17 19:40 UTC, FenixFly requested changes

2024-04-17 19:40 UTC, FenixFly commented on src/model_converters/tf2onnx/convert_tf_to_onnx.py
> +    input_shape = ast.literal_eval(args.input_shape)
конвертацию в list тоже переместите в try секцию.

2024-04-18 01:14 UTC, FenixFly requested changes

2024-04-18 01:14 UTC, FenixFly commented on src/model_converters/tf2onnx/convert_tf_to_onnx.py
> +                        'Should be in the format "[batch_size, height, width, channels]".'),
Codestyle тест выдал тут ошибку. Скорей всего строка должна начинаться на то же уровне, что и строка выше, т.е. на 6 пробелов правее
E128 continuation line under-indented for visual indent

2024-04-18 19:33 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/README.md
> +с использованием скриптов `inference_pytorch.py` и `inference_onnx_runtime.py`
Может, `inference_tensorflow.py`, а не `inference_pytorch.py`?

2024-04-19 13:32 UTC, valentina-kustikova commented on src/model_converters/tf2onnx/convert_tf_to_onnx.py
> +                        dest='graphdef')
@Vav1L0N, согласно Python API там есть несколько вариантов, в частности, keras и checkpoint. По смыслу конечно нам интересны оба этих варианта тоже.

2024-06-19 14:09 UTC, valentina-kustikova approved these changes

2024-06-19 14:09 UTC, merged